### ISSUE TITLE
[Docs] Missing Valid Namespaces Subcommand in Pulsar admin CLI Documentation

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/pulsar#10023]
**Describe the bug**
The `set-inactive-topic-policies` subcommand is only shown as a `topics` command and not as a `namespaces` command in the pulsar-admin docs: https://pulsar.apache.org/docs/en/pulsar-admin/.

I know it is a valid subcommand by looking at the source code as well as looking at the available `bin/pulsar-admin namespaces` commands.

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/en/pulsar-admin/
2. Search for `set-inactive-topic-policies`
3. Observer that it is only listed for the `topics` command

**Expected behavior**
I would expect the pulsar-admin docs to include all available sub commands.

**Additional context**
I believe these docs are generated, so perhaps something is wrong with the generation.

I'm happy to help look into this issue sometime this week, but I'm unable to do so today.

**Comment by Anonymitaet** [comment]
@michaeljmarshall The Pulsar Admin CLI page is deprecated (2.8.0: https://github.com/apache/pulsar/pull/9813, 2.7.1: https://github.com/apache/pulsar/pull/10037) since the contents of this page lag far behind code. The latest commands and descriptions of Pulsar Admin are shown on the [pulsar-admin website](http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/). Users can navigate to that site to get accurate and complete info.

**Comment by michaeljmarshall** [comment]
@Anonymitaet - I didn't realize there was a difference. Thank you for pointing that out. I think we should add some type of banner or notice at the top of that page to redirect users to the new resource. What do you think about that?

**Comment by michaeljmarshall** [comment]
> I think we should add some type of banner or notice at the top of that page to redirect users to the new resource.

I posted a review on https://github.com/apache/pulsar/pull/10037, so no need to respond here.
