### ISSUE TITLE
[Doc] Document for Reference/Pulsar Admin CLI is missing after 2.7.0 from website

### ISSUE THREAD

**Issue by MarvinCai** [apache/pulsar#10932]
As describe, document for Reference/Pulsar Admin CLI is missing starting from 2.7.1, it's still there in 2.7.0
Noticing because the warning for Inactive Topic clean up is missing: https://pulsar.apache.org/docs/en/2.7.0/pulsar-admin/#note
It's enabled by default in standalone, might cause confusion for user if they found their topic is gone but can't find out why from Pulsar doc.

**Comment by Anonymitaet** [comment]
Hi @MarvinCai Pulsar Admin CLI is removed from 2.7.1 since the docs of Pulsar Admin CLI always lag behind code. Users can get the latest info [here](http://pulsar.apache.org/tools/pulsar-admin/) which is synced up w/ code.

How about adding the instruction to these two places? 

1. [Pulsar Admin CLI](http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/)?

![image](https://user-images.githubusercontent.com/50226895/122314705-47db8e00-cf4b-11eb-9da4-fc1a54c85f3f.png)

If agree, how about adding the contents below?

If topics are not consumed for some while, these inactive topics might be cleaned up. Deleting inactive topics is enabled by default.

2. [Pulsar configuration - broker](https://pulsar.apache.org/docs/en/next/reference-configuration/#broker)

![image](https://user-images.githubusercontent.com/50226895/122315018-cafce400-cf4b-11eb-8602-a2379ec3133f.png)

If agree, how about adding the contents below?

If topics are not consumed for some while, these inactive topics might be cleaned up. Deleting inactive topics is enabled by default.

**Comment by MarvinCai** [comment]
Sounds good, probably also mention the default period (60s).

**Comment by Anonymitaet** [comment]
@MarvinCai thanks for your instruction. OK, I'll add and need your review later.
