### ISSUE TITLE
[Build] Unable to find image 'apachepulsar/pulsar-build:manylinux-cp39-cp39' locally

### ISSUE THREAD

**Issue by timmyyuan** [apache/pulsar#11004]
**Describe the bug**
Python client build error. (maybe introduced by https://github.com/apache/pulsar/pull/10954)

**To Reproduce**
1. Checkout the master branch
2. Run `pulsar-client-cpp/docker/build-wheels.sh`
3. See error

**Expected behavior**
The build succeed

**Screenshots**
```
+ auditwheel repair dist/pulsar_client-2.9.0-cp38-cp38-linux_x86_64.whl
INFO:auditwheel.main_repair:Repairing pulsar_client_sn-2.9.0-cp38-cp38-linux_x86_64.whl
INFO:auditwheel.wheeltools:Previous filename tags: linux_x86_64
INFO:auditwheel.wheeltools:New filename tags: manylinux1_x86_64
INFO:auditwheel.wheeltools:Previous WHEEL info tags: cp38-cp38-linux_x86_64
INFO:auditwheel.wheeltools:New WHEEL info tags: cp38-cp38-manylinux1_x86_64
INFO:auditwheel.main_repair:
Fixed-up wheel written to /pulsar/pulsar-client-cpp/python/wheelhouse/pulsar_client_sn-2.9.0-cp38-cp38-manylinux1_x86_64.whl
--------- Build Python wheel for 3.9 -- cp39-cp39
Using image: apachepulsar/pulsar-build:manylinux-cp39-cp39
Unable to find image 'apachepulsar/pulsar-build:manylinux-cp39-cp39' locally
docker: Error response from daemon: manifest for apachepulsar/pulsar-build:manylinux-cp39-cp39 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by lbenc135** [comment]
This is because the build image was not released yet. Maybe @BewareMyPower knows when that happens? I see no reason why we couldn't build it now, but someone with the correct rights needs to run `pulsar-client-cpp/docker/create-images.sh` and `pulsar-client-cpp/docker/push-images.sh`.

As a workaround, you can build the image locally with `pulsar-client-cpp/docker/create-images.sh`, and edit the `build-wheels.sh` script to take `pulsar-build` instead of `apachepulsar/pulsar-build`.

**Comment by tuteng** [comment]
Fixed https://hub.docker.com/layers/apachepulsar/pulsar-build/manylinux-cp39-cp39/images/sha256-7406830c7fe0afc8b9ce8b51948ef66b02bd35b7f3a0a573ea67bb4d89a59da6?context=repo
