### ISSUE TITLE
How to retry send message after send fail at async mode?

### ISSUE THREAD

**Issue by Johnnyhooyo** [apache/pulsar#11315]
![image](https://user-images.githubusercontent.com/35983936/125621225-6f2c2b4a-0043-44e7-a5b5-77759967a600.png)
The exception is queuefull.

**Comment by Johnnyhooyo** [comment]
org.apache.pulsar.client.api.PulsarClientException$ProducerQueueIsFullError: Producer send queue is full

**Comment by eolivelli** [comment]
You cannot have a messageId because the message was not sent an so there is no "message", the ID is assigned by the broker while persisting the message on BookKeeper (in fact the message id contains the ledgerId and the entryId)

**Comment by eolivelli** [comment]
you have to implement your own retry mechanism

**Comment by eolivelli** [comment]
or you can use the blockIfQueueFull feature

**Comment by Johnnyhooyo** [comment]
Do you consider returning the data what we send when fail? so that i can save this data for retry.
now, i just know something was error but i can not find out which data send fail.

**Comment by dipinhora** [comment]
i'm running into this issue also.. (note: i'm new to pulsar so it is possible i'm missing something)

i'm trying to figure out how to handle/retry `async send` failures (`timeout`/`queue full`/etc).. from what i can tell, the pulsar client (i'm using `nodejs` but things seem to function the mostly same way in other clients i've looked at so far [`cpp`/`java`]) assigns a `messageId` internally and only returns that `messageId` and an error code but not the original payload provided to the `async send` call.. 

returning the original payload as @Johnnyhooyo mentioned would solve the issue as i could then implement a retry based on the payload and there would be no ambiguity as to what message send failed..

> you have to implement your own retry mechanism

@eolivelli understood but as of right now it isn't possible to implement a retry because there doesn't seem to be any way of identifying the original payload that the failed send is for..

are there any examples of handling/retrying `async send` failures for any client (preferably `nodejs`/`c++` but others would be helpful also)?

**Comment by CoderCookE** [comment]
at least in node, and i'd imagine you can do something similar in Java, if you wrap the `send` method you'll have the `msg` in scope for your catch method to do whatever you want with on error.

```
exports.publish = async function(message, timestamp) {
  const producer = await client.createProducer(producerConfig);
  const msg = {
    data: Buffer.from(message),
    eventTimestamp: timestamp
  };

  producer.send(msg).catch(function(err) {
    log.error({ message: `Error publishing: ${err}; dropping message`,  msg: msg });
  });
};```

**Comment by eolivelli** [comment]
@CoderCookE idea is good.

In Java you can "capture" the variables outside your function.

```
final var payload = ....;
CompletableFuture<MessageId> handle = producer.send(payload);
handle.whenCompleteAsync( (mid, error) -> {
   if (error != null) {
        logger.error("Error sending {}", payload);
   }
});

```
probably a better style is:
```

class SendCompletionHandler implements BiConsumer<MessageId, Throwable> {
    Object payload;
    void accept(MessageId id, Throwable error) {
            if (error != null) {
        logger.error("Error sending {}", payload);
   }
    } 
}

final var payload = ....;
SendCompletionHandler errorhander = new SendCompletionHandler(payload);
CompletableFuture<MessageId> handle = producer.send(payload);
handle.whenCompleteAsync(errorhander);
```

**Comment by dipinhora** [comment]
@CoderCookE @eolivelli thanks for the idea and examples.. i can't believe i missed that..

**Comment by Johnnyhooyo** [comment]
Wow!~ @CoderCookE @eolivelli thanks very mach for help~~ i got it~ then i close this issue.
