### ISSUE TITLE
General questions on Pulsar -  leader broker and ZK performance issues.

### ISSUE THREAD

**Issue by rayliu419** [apache/pulsar#11698]
Hi team, 

I can't find a template to ask general question so I just post it here, please direct me to the right template/place if I am wrong. 

1. Kafka(<2.8) use ZK to do leader broker election, as far as I know, when doing rolling update, when the leader broker update, the kafka cluster needs to select a new leader. During the time, the whole cluster can't offer service(at least not for write). I searched some pages and found Pulsar also has a concept called leader broker, does that also happens in Pulsar? 

2. It seems Pulsar use ZK a lot, e.g., store meta data such as topic/namespace/tenants information, does that affect the cluster performance when the cluster is large? The configuration rarely changes so I think that's OK, but the meta data such as consumer offset change frequently, so I guess ZK will be a bottleneck of the whole cluster? 

Thanks, 

Rui

**Comment by liangyuanpeng** [comment]
Slack is good place of talk about this.

**Comment by rayliu419** [comment]
@liangyuanpeng , thanks for your suggestion, I just joined it.

**Comment by eolivelli** [comment]
@liangyuanpeng @rayliu419 

> Slack is good place of talk about this.
This is good, but in Apache we usually prefer to discuss on the mailing lists, like users@pulsar.apache.org (subscribe here https://pulsar.apache.org/contact/)

This is because in the mailing lists the discussion is more asynchronous and more people are able to interact with the discussion thread.
Slack is very good for quick answers/replies and possibly targeted to specific persons

see you on Slack or in the ML

**Comment by rayliu419** [comment]
close the issue.
