### ISSUE TITLE
[Pulsar admin] admin command 'get-message-by-id' can get message by messageId regardless of topic name

### ISSUE THREAD

**Issue by zhanghaou** [apache/pulsar#11814]
![image](https://user-images.githubusercontent.com/5668441/131091854-f756ba41-5ad3-4082-a541-6c78120285ab.png)

**Comment by eolivelli** [comment]
@zhanghaou 
thank you for sharing this finding.

this bug looks like a security issue.
please take into consideration to file a "Security report" for the next time.
This issue is disclosing a potential security risk to a wide audience.

the correct process is to send an email to security@apache.org or to private@pulsar.apache.org

we will follow up with a release soon

**Comment by zhanghaou** [comment]
> @zhanghaou
> thank you for sharing this finding.
> 
> this bug looks like a security issue.
> please take into consideration to file a "Security report" for the next time.
> This issue is disclosing a potential security risk to a wide audience.
> 
> the correct process is to send an email to [security@apache.org](mailto:security@apache.org) or to [private@pulsar.apache.org](mailto:private@pulsar.apache.org)
> 
> we will follow up with a release soon

OK.
