### ISSUE TITLE
Can not found doc for "Enable pulsar function to send message to external pulsar cluster "

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/pulsar#11855]
Please answer the following questions before submitting your doc issue. Thanks!

# What issue do you find in Pulsar docs?

Not found doc about this PR https://github.com/apache/pulsar/pull/8434

# What is your suggestion?

Add explanations or use case about this on https://pulsar.apache.org/docs/en/functions-overview/

# Do you have any references?

# Would you like to fix this issue?

No, I want to try this feature and got nothing. have not idea for it.  

# Other

Try `bin/pulsar-admin functions` and not found `--external-pulsars`

Pulsar Version: 2.8.1

**Comment by Anonymitaet** [comment]
@liangyuanpeng thanks for your issue. Since the PR https://github.com/apache/pulsar/pull/8434 was already labeled with `doc-required`, there is no need to label this issue with `doc-required` again, so I close this issue. We will add docs later.

If you have any problems in using this feature, you can create another issue, thanks.
