### ISSUE TITLE
Docs clarification needed for concepts-messaging/#retry-letter-topic

### ISSUE THREAD

**Issue by alexsapps** [apache/pulsar#12053]
I find the [Retry letter topic](https://pulsar.apache.org/docs/en/next/concepts-messaging/#retry-letter-topic) docs confusing. Here are some questions:

 * Is it really the producer's responsibility to send the message to the retry topic? The docs say "you can configure the producer to send messages to both the business topic and the retry letter topic". If this is accurate, should the producer send to both topics at the same time or only push to retry topic after business topic fails?
 * In the code example with `.retryLetterTopic`, does the consumer get both business and retry messages in the same stream? Are retried messages delivered interleaved with business messages based on timestamps, or does the subscription prioritize one topic over the other?
 * What is the relationship between retryLetterTopic and enableRetry? (Is retryLetterTopic ignored when enableRetry is false? Is it an error to specify a retryLetterTopic when enableRetry is false?)
 * What is "retrial queue" (`reconsumeLater`) ? Is it different than a retry topic?
 * Is `reconsumeLater` different from throwing an exception that causes the message to go to the retryLetterTopic?
 * What is maxRedeliverCount – is “redeliver” different from “retry”? Is it the number of times it tries to redeliver immediately before putting it in the retry queue, or the number of times it gets put back into the retry queue before going to the dead letter topic?
* The sentence starting "To configure the delay time" does not actually say how or where to specify a delay time. But I assume it is a global setting on the retry topic?

**Comment by alexsapps** [comment]
If somebody answers the questions here I can try sending a PR.

Really great to have built-in retries. Thank you!

@Huanli-Meng @liudezhi2098  :)

**Comment by Huanli-Meng** [comment]
@alexsapps thanks for pointing these questions out and I will ping related engineers to see if they can clarify these issues?

**Comment by alexsapps** [comment]
That would be great @Huanli-Meng, thank you!

**Comment by liudezhi2098** [comment]
@alexsapps retry topic scene is mainly to customize different delay intervals for consumers. Of course, you can handle the failed actions by themselves, but in fact, this can be encapsulated and the experience is better.

**Comment by alexsapps** [comment]
Hi Liudezhi, I'm not sure I understand your comment. What does "scene" mean here? What do you mean handling failed actions "by themselves" - as opposed to what? What can be encapsulated?  Thanks!

**Comment by liudezhi2098** [comment]
I’m sorry I didn’t get here in time.

Retry topic scene is mainly traditional business logic, such as when processing a message fails, the user wants to be able to customize the delay time to process the failed message, such as 1 second, 5 seconds, 10 seconds, it could be any number.

these actions can be implemented in logic, such as having the producer delay sending this message to the current topic or another topic when processing the business logic fails, and then having the consumer process it again. I think this is a common processing mode, so  can add it to the client api.

the current approach is to put deferred messages into another Topic of subscriptionName-RETRY, because the business retry message is only relevant to the current subscriber.
