### ISSUE TITLE
I want to write cross-platform c++ software. I want to get some binary library in different platform

### ISSUE THREAD

**Issue by kenlxh11** [apache/pulsar#12391]
I want to get unix ,windows 10 32bit and 64bit, mac binary library

**Comment by wmccarley** [comment]
Compiling the c++ client library is possible on all of the [platforms you listed.](https://pulsar.apache.org/docs/en/client-libraries-cpp/#supported-platforms) The Windows client you will have to compile yourself. The last time I tried to do that was a year ago and it was super not fun... all sorts of issues with the dependencies (openssl, a few others.) However, it looks from the docs like the build process may have been improved since then so maybe you are golden :) -- try it out see if it works.

**Comment by tisonkun** [comment]
Closed as stale. The development of the C++ client has been permanently moved to http://github.com/apache/pulsar-client-cpp. Please open an issue there if it's still relevant.
