### ISSUE TITLE
How to debug the code of pulsar broker In IDE ?

### ISSUE THREAD

**Issue by ooooo-youwillsee** [apache/pulsar#12406]
I want to contribute code, I can't luanch pulsar server in IDE,

I hope have a developer document which teach me to lauch `PulsarBrokerStarter`  , `XXXStarter` and so on.

**Comment by BewareMyPower** [comment]
> then stoping program, again lauch PulsarStandaloneStarter for the sencond time. Here is log in console.

You can remove the `data` directory first. But I think the error logs doesn't affect. Each time a standalone starts, it tries to create the cluster metadata in ZK. See `createSampleNameSpace#createSampleNameSpace`. Maybe you can enhance the start process of standalone.

Regarding to the JVM arguments, I have nearly not configured them for development. The error might be caused by the class path issue.

> I really want to know How you set the development environment when developing pulsar in idea.

Just add a test or run an existing test in `SimpleProducerConsumerTest`.

![image](https://user-images.githubusercontent.com/18204803/138019022-99883e91-a83e-4044-be12-e6dc8be878ef.png)

![image](https://user-images.githubusercontent.com/18204803/138019180-07a61d8f-a161-4e2b-887d-19165435dd4b.png)

**Comment by ooooo-youwillsee** [comment]
thanks

**Comment by leizhiyuan** [comment]
or you can add  one line 
```
OPTS="$OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
```

in bin/pulsar 

then, you can run pulsar in local machine,  https://pulsar.apache.org/docs/en/standalone/ 
and debug remotely in ide

![image](https://user-images.githubusercontent.com/2684384/140483024-bede93a0-579a-4b4c-87ac-badf9bce453a.png)

**Comment by tisonkun** [comment]
Closed as answered. We now have a developer guide page describing how to set up an IDE https://pulsar.apache.org/contribute/setup-ide
