### ISSUE TITLE
Increase number of bundles if a topic has huge number of partitions.

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#1253]
If a topic is created with huge number of partitions, it would be good to increase number of bundles by default.

**Comment by rdhabalia** [comment]
I think based  on the few past performance tests, we realized that bundle with 1K topic doesn't have much performance impact and if user creates topic with > 1K partitions then [Load-manager](https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L370) will split the bundle if bundle has some good amount of traffic. Actually, adding more bundles will add more znodes in zookeeper and we may want to avoid zk-node creation if it doesn't require.?

**Comment by merlimat** [comment]
> If a topic is created with huge number of partitions, it would be good to increase number of bundles by default. 

It is already the default behavior, though it happens after the creation of all the partitions, since before there's no way how many will be created. 

The default setting is to keep "splitting" bundles until there are < 1K topics/partitions in each. By default, too, we force unload of those bundles to spread them across available brokers. 

One thing that is not really clear from the documentation is how to prepare upfront for this kind of scenarios and create multiple bundles when creating the namespace.

**Comment by merlimat** [comment]
> This might be much better for the use cases that have high number of partitions: split during creation vs split during runtime.

Yes, ideally if one creates a topic with 4000 partitions.. it would be better to have enough bundles before the user starts using them. 
Currently the problem is that the "create-partitioned-topic" operation just sets the metadata and the partitions are actually created when producers/consumers connect.

We could improve the `create-partitioned-topic` op to actually ensure there are enough bundles.

> or it might be good to have a large number for default bundles?

That is possible in 2 ways : 
  * `defaultNumberOfNamespaceBundles=4` in `broker.conf`
  * `pulsar-admin namespaces create $MY_NAMESPACE --bundles 64`

In both cases, we need documentation for one to understand what is that and why it matters.

**Comment by sijie** [comment]
> We could improve the create-partitioned-topic op to actually ensure there are enough bundles.

ah, that's what I meant to request for this issue.

**Comment by sijie** [comment]
@rdhabalia I think the tradeoff here is whether you pay the penalty of spitting bundles at creation time or at runtime. I agreed splitting is definitely better on resources. However it is also good for users to do "pre-split" at creation time before run. 

I am wondering can we have some sort of split policies, that allows people can pre-split at creation time?
