### ISSUE TITLE
The python pulsar client creates a producer and then closes the producer. The memory will not be released

### ISSUE THREAD

**Issue by 609101723** [apache/pulsar#12618]
Just like issue #12408, I raised a question. I kept creating and closing producers, but the memory would not be released. I saw that the problem had been solved. When I re installed pulsar client with PIP, I found that the program would be released when I ran the program for the first time, and the memory would not be released when I closed the program for the second time
The procedure is as follows(I installed it using pip3)：
import pulsar

StrPulsar = "pulsar://192.168.1.2:30771"
StrTopic = "Test"

while True:
pulsarClient = pulsar.Client(StrPulsar, operation_timeout_seconds = 3)
producer = pulsarClient.create_producer(StrTopic, send_timeout_millis=3000)
producer.close()
pulsarClient.close()

**Comment by merlimat** [comment]
@609101723 The PR #12409 was marked for 2.10.0, 2.9.1 and 2.8.2 releases and none of them were released yet.

**Comment by 609101723** [comment]
Which version will be released? When will it be released? Otherwise I can't use this module now

**Comment by 609101723** [comment]
> @609101723 The PR #12409 was marked for 2.10.0, 2.9.1 and 2.8.2 releases and none of them were released yet.

Which version will be released? When will it be released? Otherwise I can't use this module now

**Comment by codelipenghui** [comment]
@609101723 Both 2.8.2, 2.9.1, and 2.10.0 will have this fix, the 2.8.2 release is in progress now, maybe it will available in 2 weeks, if you want a quick fix, here is an earlier release based on the branch-2.8 https://github.com/streamnative/pulsar/releases/tag/v2.8.1.20

Since the bug has been fixed, so I will close the issue first. Feel free to reopen it if the new fix does not work.
