### ISSUE TITLE
[Website] generate website for C client API 

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#12843]
# Background

Currently, we have [API websites for various languages](https://pulsar.apache.org/api/), such as the Java / C++ / Python API website.

# Issue

1. C does not have an API website.
`.h` files of C are available at [here](https://github.com/apache/pulsar/tree/master/pulsar-client-cpp/include/pulsar/c).
@BewareMyPower found that Doxygen generates C++ rather than C API website. 

2. C lacks many descriptions.

Example:
![image](https://user-images.githubusercontent.com/50226895/142132878-9644a2d0-71ed-4e37-bd03-9708e9245055.png)

# Solution

1. Generate a website for C client API

2. Add missing descriptions for C 

>>>>>>>>>>

Anyone would like to help? Thanks

**Comment by merlimat** [comment]
@Anonymitaet The C API is packaged together with the C++ client library. I think it's because of the Doxygen configuration that it's not considering the C headers for documentation. In particular, it could be just that we need to add the directory on https://github.com/apache/pulsar/blob/6704f12104219611164aa2bb5bbdfc929613f1bf/pulsar-client-cpp/Doxyfile#L812

**Comment by tisonkun** [comment]
This can be relevant to #17498
