### ISSUE TITLE
org.apache.pulsar.broker.web.AuthenticationFilter Filter Out WebSocket with authentication token in query.

### ISSUE THREAD

**Issue by YouJiacheng** [apache/pulsar#12912]
Just Like #12303
But if authentication token in header, everything is fine, thus I guess that problem is caused by org.apache.pulsar.broker.web.AuthenticationFilter.

**Comment by mattisonchao** [comment]
@codelipenghui  i want to work on it.

**Comment by tisonkun** [comment]
Closing as stale. If it's still relevant to maintained versions, feel free to open a new issue.

I read #12303 and cannot understand what is "just like" and "but if ...". Please provide a complete reproduce if you open a new issue. Otherwise, it's hard for the maintainers to understand what is the trouble you were facing.

**Comment by tisonkun** [comment]
FWIW - https://github.com/apache/pulsar/pull/14044 may fix this issue.
