### ISSUE TITLE
When will Python 3.10 be supported

### ISSUE THREAD

**Issue by thecodeway** [apache/pulsar#13278]
Pulsar Python client 
from the doc(https://pulsar.apache.org/docs/en/client-libraries-python/), highest support version was  python 3.8(linux)、python 3.(mac).
My current version is 3.10. I hope it can be supported

**Comment by sarimak** [comment]
I was missing support for Linux, Python 3.9 and pulsar-client 2.8.1 and I was able to compile the wheel myself (using Ubuntu 21.10). Perhaps you could do the same for 3.10 in the meantime.

I checked out this Git repo, switched to v2.8.1 tag and back-ported the diff from pull request which introduced the dockerized build for Python 3.9 (which has to use manylinux2014 instead of manylinux1 due to an upstream library): https://github.com/apache/pulsar/pull/10954/files

Then I simply ran docker-build.python3.9.sh in pulsar-client-cpp folder and waited over an hour.

**Comment by sarimak** [comment]
Since the build script is using PyPA's official base Docker image for manylinux wheels, it could be just a matter of changing the `PYTHON_VERSION="3.9"` and `PYTHON_SPEC="cp39-cp39"` to 3.10 (in the build script) and adding it to `PYTHON_VERSIONS` (both in build-wheels.sh and create-images.sh).

Since the whole build happens inside the Docker image, there is no need to install C++ libraries on your physical workstation. The final step which is running the `auditwheel repair` failed for me (wrong commandline arguments I think) but I think it is not needed for the build itself.

**Comment by thecodeway** [comment]
Thank you for your reply. I'll try as you say

**Comment by holdlg** [comment]
> I was missing support for Linux, Python 3.9 and pulsar-client 2.8.1 and I was able to compile the wheel myself (using Ubuntu 21.10). Perhaps you could do the same for 3.10 in the meantime.
> 
> I checked out this Git repo, switched to v2.8.1 tag and back-ported the diff from pull request which introduced the dockerized build for Python 3.9 (which has to use manylinux2014 instead of manylinux1 due to an upstream library): https://github.com/apache/pulsar/pull/10954/files
> 
> Then I simply ran docker-build.python3.9.sh in pulsar-client-cpp folder and waited over an hour.

manylinux2014 does not support python 3.10.
However,the new manylinux is based on Debian 9.    https://github.com/pypa/manylinux

**Comment by merlimat** [comment]
@thecodeway @sarimak @holdlg Closing this since we now have 3.10 packages available

**Comment by JanVosNL** [comment]
@thecodeway

Python bindings for Apache Pulsar is available on Alpine Linux

```
# apk search pulsar-client
py3-pulsar-client-cpp-2.9.1-r0
pulsar-client-cpp-static-2.9.1-r0
pulsar-client-cpp-2.9.1-r0
pulsar-client-cpp-dev-2.9.1-r0

# apk info py3-pulsar-client-cpp
py3-pulsar-client-cpp-2.9.1-r0 description:
Python bindings for Apache Pulsar C++ client

py3-pulsar-client-cpp-2.9.1-r0 installed size:
4996 KiB

# apk info pulsar-client-cpp
pulsar-client-cpp-2.9.1-r0 description:
Apache Pulsar C++ client

pulsar-client-cpp-2.9.1-r0 installed size:
3168 KiB

# apk add py3-pulsar-client-cpp
(1/1) Installing py3-pulsar-client-cpp (2.9.1-r0)

# python3 --version
Python 3.10.3
```
