### ISSUE TITLE
Split FutureUtils in to dedicated mvn package?

### ISSUE THREAD

**Issue by cnmade** [apache/pulsar#13325]
https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java

The source code is a very good Future library , i never found any other library like it.
I also want to use it for our projects.

I wonder to know, may your please release it under a dedicated mvn package?

We only need the Future, Not the whole pulsar-common

**Comment by tisonkun** [comment]
Thanks for reporting your use case @cnmade!

There is no plan for such releasing. But since it's no more than one source file which is accessible under the Apache License 2.0 which allows you to freely use, modify and distribute, you can simply copy the code for your usage - remember to keep the license header.
