### ISSUE TITLE
No subscription metrics for non persistent topic consumer

### ISSUE THREAD

**Issue by dragonls** [apache/pulsar#13645]
**Describe the bug**
It seems that there are no subscription throughput out metrics for non persistent topic consumer, which make it hard to know whether the consumers are working fine.

I tried to produce and consumer a non persistent topic. The metrics `pulsar_subscription_msg_throughput_out` and `pulsar_throughput_out` are always 0 for non persistent topics, but work correctly for persistent topics.

**To Reproduce**
1. Create a non persistent topic
2. Try to produce and consume the topic
3. See the metrics `pulsar_subscription_msg_throughput_out` and `pulsar_throughput_out`

**Expected behavior**
See the throughput out of the topic and each subscription.

**Screenshots**
![image](https://user-images.githubusercontent.com/2565118/148348682-e21c385b-b688-48e9-9024-4846c2d3416b.png)
![image](https://user-images.githubusercontent.com/2565118/148348816-10008f61-0ac7-41b0-b1b9-4fd2d633f887.png)

**Additional context**
Pulsar version: 2.7.2

**Comment by mattisonchao** [comment]
i can work on it.

**Comment by tongsucn** [comment]
> i can work on it.

@mattisonchao Hi, the problem still exists on Pulsar 2.8.2.

I think the problem locates at `org.apache.pulsar.common.policies.data.stats.NonPersistentTopicStatsImpl`. It owns a map object `subscriptions` which "overwrites" the parents' one.

In `org.apache.pulsar.broker.service.nonpersistent.NonPersistentTopic.getStats`, subscription information are updated to `NonPersistentTopicStatsImpl.subscriptions` rather than `TopicStatsImpl.subscriptions`.

But `org.apache.pulsar.broker.stats.prometheus.NamespaceStatsAggregator.getTopicStats` uses `TopicStatsImpl.subscriptions` to generate Prometheus metrics.
