### ISSUE TITLE
Version 2.9.1 pulsar-client (python )is not available for Mac

### ISSUE THREAD

**Issue by zhavir** [apache/pulsar#14148]
**Describe the bug**
Version 2.9.1 of the pulsar-client (python ) is not available for Mac

**To Reproduce**
pip install pulsar-client==2.9.1

`ERROR: Could not find a version that satisfies the requirement pulsar-client==2.9.1 (from versions: 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.3, 2.7.0, 2.7.1, 2.7.2, 2.7.2.post0, 2.7.3, 2.8.0, 2.8.0.post0)
ERROR: No matching distribution found for pulsar-client==2.9.1
`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs BigSur 11.6

**Additional context**

**Comment by dmytro-audibene** [comment]
having same issue

**Comment by whisust** [comment]
Same.
I need to upgrade to 2.8.0, dev on macos and the CI build is on Linux.
I can't do this because:
- `pulsar-client==2.8.0` can not be used locally due to the dynamic linking error (which triggered `2.8.0.post0`, but works on CI
- `pulsar-client==2.8.0.post0` can be used locally, but does not exist in the CI build

**Comment by zhavir** [comment]
Same on Mac OS Monterey

**Comment by zhavir** [comment]
same for the pulsar-client 2.10

**Comment by zhavir** [comment]
> @zhavir `pulsar-client` 2.10.0 is available for Mac for Python 3.7, 3.8, 3.9 and 3.10: https://pypi.org/project/pulsar-client/#files for Intel and ARM.
> 
> Which versions are you trying to use?

oh! you're right, yesterday I was getting errors while trying to get the latest version of the pulsar-client on my Mac OS Monterey. Thanks!

**Comment by zhavir** [comment]
> @zhavir `pulsar-client` 2.10.0 is available for Mac for Python 3.7, 3.8, 3.9 and 3.10: https://pypi.org/project/pulsar-client/#files for Intel and ARM.
> 
> Which versions are you trying to use?

ok, now I get which version is missing. I was trying to pull the 2.7 version for ARM. It is missing also from [here](https://pypi.org/project/pulsar-client/#files) as you can see

**Comment by merlimat** [comment]
We’re removing support for Python 2.7 at this point, so there will be no more wheel files published. https://github.com/apache/pulsar/issues/15185

**Comment by zhavir** [comment]
It makes sense, but why the build is missing only for ARM architecture?

**Comment by merlimat** [comment]
We have these wheel files for Pulsar 2.10.0 on Mac: 

 * pulsar_client-2.10.0-cp37-cp37m-macosx_11_0_x86_64.whl 
 * pulsar_client-2.10.0-cp38-cp38-macosx_11_0_universal2.whl 
 * pulsar_client-2.10.0-cp39-cp39-macosx_11_0_universal2.whl 
 * pulsar_client-2.10.0-cp310-cp310-macosx_11_0_universal2.whl 
 
 The `universal2` wheels include x86_64 and arm binaries. 

For Python 3.7, we only have intel binaries since it does not support ARM on MacOS (which was only added in Python 3.8+). This is being discussed in #15402.

**Comment by zhavir** [comment]
Same problem for pulsar client 2.10 and macOS 12.3.1

**Comment by tisonkun** [comment]
Closed as stale. The development of the Python client has been permanently moved to https://github.com/apache/pulsar-client-python. If this is still relevant, please open an issue there.
