### ISSUE TITLE
[Doc] [pulsar-io]  Missing documentation for the BatchSource interface for Pulsar IO

### ISSUE THREAD

**Issue by hsaputra** [apache/pulsar#14561]
#### Expected behavior

Have a public documentation for the new BatchSource interface in Pulsar IO module:

https://github.com/apache/pulsar/wiki/PIP-65%3A-Adapting-Pulsar-IO-Sources-to-support-Batch-Sources

#### Actual behavior

There is no documentation about the BatchSource interface 

#### Steps to reproduce

Looking at the latest documentation page for Pulsar IO and missing the info how to leverage BatchSource interface:
https://pulsar.apache.org/docs/en/io-develop/

#### System configuration
N/A

**Comment by hsaputra** [comment]
FYI @sijie , @merlimat , @jerrypeng

**Comment by momo-jun** [comment]
PIP-65 was implemented in #7090. @nlu90 @freeznet do you have any doc inputs for this PR?

//cc @Anonymitaet. May need to add a `doc-required` label to #7090.

**Comment by Anonymitaet** [comment]
@hsaputra adding a "how-to" doc for each interface is an unfeasible solution (e.g., adding a tutorial for every interface to https://pulsar.apache.org/docs/en/io-develop/) since it involves too much effort.

Instead, we show the usage of interfaces on the Java admin reference doc. If you want to know how to use the BatchSource interface, please check [this reference doc](https://pulsar.apache.org/api/admin/2.11.x/org/apache/pulsar/common/io/BatchSourceConfig.html). And I'll close this issue if there are no more concerns.

/cc @srkukarni

**Comment by Anonymitaet** [comment]
Close this issue as there are no more comments. cc @D-2-Ed
