### ISSUE TITLE
Class version conflicts in Pulsar Functions runtime image dependencies

### ISSUE THREAD

**Issue by noelo** [apache/pulsar#14697]
**Describe the bug**
If you build a pulsar function with a different pulsar client version than the one shipped in the Kubernetes function runtime a 
java.lang.IncompatibleClassChangeError: Implementing class exception is thrown.

**To Reproduce**
Build a function using pulsar libraries using 2.9.1.
The function will use the context and require the pulsar-client dependency
Deploy the function to a kubernetes runtime which contains an earlier version of pulsar (at time of writing 2.7.4).
Trigger the function and the "java.lang.IncompatibleClassChangeError: Implementing class exception" is thrown.

To fix ensure that you build the function with the same version as in the runtime e.g. 2.7.4

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mkoertgen** [comment]
@noelo That's right, because somewhere between 2.7 -> 2.9 the base image changed the java base version from Java 1.8 to Java 11. 
Also the ANSI-Charset in the default image changed. We also had some breaking issues with this (function user config piped as json on the command line)

Ways to accommodate this 

- Upgrade pulsar to 2.9.3/2.9.4 (helm)
- Only upgrade the function worker images to a newer version (https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml#L186)

**Comment by noelo** [comment]
cheers thanks for this @mkoertgen
