### ISSUE TITLE
[Doc] Remove Elasticsearch sink obsolete documentation page

### ISSUE THREAD

**Issue by vroyer** [apache/pulsar#14695]
### What issue do you find in Pulsar docs?

This elasticsearch sink [page](https://pulsar.apache.org/docs/en/io-elasticsearch/) is obsolete.
The right one is now this [page](https://pulsar.apache.org/docs/en/io-elasticsearch-sink/).

### What is your suggestion?

Remove the obsolete page https://pulsar.apache.org/docs/en/io-elasticsearch/

### Do you have any references?

https://www.datastax.com/products/luna-streaming

### Would you like to fix this issue?

Yes, remove the [io-elasticsearch.md](https://github.com/apache/pulsar/blob/master/site2/docs/io-elasticsearch.md)

### Note

- [X] I have researched my question.

**Comment by Anonymitaet** [comment]
@vroyer please do not delete [io-elasticsearch.md](https://github.com/apache/pulsar/blob/master/site2/docs/io-elasticsearch.md) because other places might reference that file.
Instead, you can update https://pulsar.apache.org/docs/en/io-elasticsearch/ with https://pulsar.apache.org/docs/en/io-elasticsearch-sink/.

**Comment by momo-jun** [comment]
I've checked both master and versioned docs, the `io-elasticsearch.md` file is not referenced now.

Regarding this `io-elasticsearch.md` topic, is it still in use? It is not displayed in the left navigation (not in the sidebar.json).

**Comment by eolivelli** [comment]
@nicoloboschi can you help here please ?

**Comment by nicoloboschi** [comment]
@momo-jun @Anonymitaet both https://pulsar.apache.org/docs/io-elasticsearch-sink/ and https://pulsar.apache.org/docs/io-elasticsearch/ are obsolete. We can remove them. It's better to have a not found page instead of very old page.

The official page is https://pulsar.apache.org/docs/next/io-elasticsearch-sink#configuration
