### ISSUE TITLE
what is the mean skipListArenaChunkSize,skipListArenaMaxAllocSize,skipListSizeLimit

### ISSUE THREAD

**Issue by armandxu** [apache/pulsar#14705]
what is the mean skipListArenaChunkSize,skipListArenaMaxAllocSize,skipListSizeLimit in bookkeeper.conf

**Comment by dao-jun** [comment]
In my understanding:

skipListSizeLimit: It means how many entries can be added in a `EntryMemTable`

skipListArenaChunkSize: It means the memory size of a `Chunk`(a heap memory pool, to avoid frequently memory allocation and a lot of memory fragments). When bookie received an entry, the entry exists in `direct memory`, so that it needs to copy into heap memory(Chunk).

skipListArenaMaxAllocSize: It means the threshold of an entry can be copy into `Chunk`. If an entry's size is greater than `skipListArenaMaxAllocSize`,  bookie will be allocated heap memory by invoke `new byte[size]` directly.

**Comment by tjiuming** [comment]
In my understanding:

skipListSizeLimit: It means how many entries can be added in a `EntryMemTable`. Entries will be cached in heap memory first, then async flush into disk.

skipListArenaChunkSize: It means the memory size of a `Chunk`(a heap memory pool, to avoid frequently memory allocation and a lot of memory fragments). When bookie received an entry, the entry exists in direct memory, so that it needs to copy into heap memory(`Chunk`).

skipListArenaMaxAllocSize: It means the threshold of an entry can be copied into `Chunk`. If an entry's size is greater than `skipListArenaMaxAllocSize`, bookie will be allocated heap memory by invoke `new byte[size]` directly.

**Comment by momo-jun** [comment]
Hi @armandxu, the explanation for `skipListArenaChunkSize` and `skipListArenaMaxAllocSize` can also be found in https://pulsar.apache.org/docs/en/reference-configuration/.

Hi @tjiuming, thanks for providing more information. 
The `skipListSizeLimit` parameter is missing in the reference-metric.md file. Can you pls help add it next time when you submit a PR for #15439 ?

**Comment by momo-jun** [comment]
There was an attempt and discussion about adding`skipListSizeLimit` to the docs. The conclusion is that this config is not recommended to be used and we'd better not introduce any unused configurations in the docs. Refer to the [comment](https://github.com/apache/pulsar/pull/16641#discussion_r925254911) and close the issue.
