### ISSUE TITLE
Does plusar support key-shared producer?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/pulsar#15399]
Such as title.

**Comment by Shoothzj** [comment]
What effect do you want to achieve? Key-shared is kind of a policy broker dispatch to consumers.

**Comment by dragon-zhang** [comment]
Send order-message faster. Most scenarios do not require a `global order` at the queue level.

**Comment by zbentley** [comment]
I'm not quite sure what you're asking. 

If you mean "can I produce messages with common keys in a topic such that they are delivered in order", then yes; if you use a key-based batcher for your producer and publish multiple messages with the same key, they will be delivered in order to a single [KeyShared consumer](https://pulsar.apache.org/docs/en/concepts-messaging/#key_shared). 

If you mean "can I speed up the publication of messages with a common key in a topic by removing the need that messages with a key be causally ordered with all other messages in the topic", then yes, but it isn't due to key-shared behavior exclusively. There are two mechanisms to improve the performance of keyed messages (while retaining order for KeyShared consumers): topic partitioning, and batching. Increasing the partition count of your topic and/or increasing the batch/flush size of your producer will improve throughput (assuming your bottleneck was publication to a single topic and not something else, like a contended bookie handling other topics' work). That throughput improvement will happen regardless of whether or not you are using key-shared behavior, and will always compromise strict ordering unless a key-based batcher is used. If a key-based batcher is used, the likelihood of different keys going to different partitions (and being batched and flushed in separate threads/connections inside the client) is high but not 100%. Using a different partition and a different client connection/IO thread improves performance.

Does that help, or was your question about something else?

**Comment by dragon-zhang** [comment]
For example, there are topic 1(this topic has only 1 partition) and 5 messages:
1. message1、2、3 with `key1`;
2. message4、5 with `key2`;

There is no need to guarantee the "global order" of key1 messages and key2 messages, the global order such as `1 2 3 4 5`.

But need to guarantee the order of key1 messages and key2 messages, examples of qualified message sequences are as follows:
4 5 1 2 3
4 1 5 2 3
4 1 2 5 3
4 1 2 3 5
1 4 2 3 5
1 4 2 5 3

see? 4 is always before 5, and 1、2 is always before 3.

**Comment by zbentley** [comment]
That makes sense. The second answer I posted above is applicable, then. You should either:
- Add partitions to the topic.
- Use a key-based batcher in your producer with multiple IO threads.
- Use multiple producers.

Unless you use multiple partitions (or multiple topics), Pulsar will still totally order your messages according to their timestamps. If you truly want these messages to be handled fully in parallel at every level (i.e. they can be received by Pulsar in parallel, stored to BookKeeper in parallel, etc.), you must use multiple partitions or multiple topics.

With multiple partitions and a key-based batcher, there is a high probability of the full parallelism you describe wanting. With multiple topics and multiple producers (or multiple producers on a partitioned topic with a custom batcher which guarnatees that `key1` and `key2` go to separate partitions) that probability approaches 100%. However, in my opinion the latter approach increases complexity for minimal gain.


However, I would urge you to benchmark to be sure that there really is a limitation on throughput in your base case. Pulsar's internal imposition of global ordering and store operations are already highly performant and parallelized internally. If you are seeing bottlenecks, I suspect that it is not due to "global ordering" being imposed on messages, and is instead due to the throughput limitations of a single-partition topic in general (likely at the storage layer; try running a reduced persistence config or a non-persistent topic to prove this out), in which case partitioning is the way to go.

**Comment by dragon-zhang** [comment]
Thanks for your patience, zbentley. `Pulsar will still totally order your messages according to their timestamps`, I got it and I want to ask one more question: if sorting is not considered and there is `only one partition`, can key1 messages and key2 messages be written to `native memory` in `parallel`? I guess not.

**Comment by zbentley** [comment]
I'm not sure; two things are in play:
- How much sorting Pulsar actually does, after messages arrive at the broker. I suspect that the answer is "not much", and that messages are causally ordered based on when they arrive at either the broker or BookKeeper. I'd be surprised if there were much in the way of "loop over all messages that have arrived recently and reorder them", but you'd have to ask a maintainer, or check the source, to be sure.
- How much parallelism is in play in the broker, when it comes to a single topic's stream of data with regards to direct memory (assuming this is what you mean by "native memory"). My assumption is "enough to minimize naïve single-thread bottlenecks", but I'm not sure. If your concern is performance, I suggest benchmarking. If your concern is whether or not the architecture isolates two keyed streams of messages, I'd suggest partitioning--doing so can guarantee that two keys are handled by two topics (and, if you manually massage topic/broker ownership, it can guarantee that the two topics are handled by fully separate brokers, depending on your configuration).

**Comment by dragon-zhang** [comment]
`partition`, copy that.
