### ISSUE TITLE
[admin] Inconsistent response in GET namespace deduplication REST API endpoint

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#16024]
## How it works now

If deduplication wasn't set, it returns `undefined`.

After `pulsar-admin namespaces set-deduplication --enable public/default` it returns `true`.

Then after `pulsar-admin namespaces set-deduplication --disable public/default` it returns `false`.

So there are three possible values: `undefined`, `true`, and `false`.

## What I expect

I would expect `true` and `false` values here.

**Comment by Technoboy-** [comment]
https://github.com/apache/pulsar/issues/9216
Since the topic-level policy is introduced, users need a specific value (null) to determine whether a policy has been set at the topic-level. Otherwise, for this boolean type of policy, if it returns false, it is difficult to determine whether it is a topic-level policy or a namespace-level policy.

**Comment by visortelle** [comment]
@Technoboy- Thank you for the response. It explains the reason, but probably it would be better to return something like:

```
{
  "enabled": boolean,
  "policyLevel": "namespace" | "topic"
}
```
