### ISSUE TITLE
[Doc] Cluster-level failover shouldn't be part of Java client chapter

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#17433]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

When I read the Java client document, I found a very long chapter to introduce [cluster-level failover](https://pulsar.apache.org/docs/next/client-libraries-java#cluster-level-failover). Seems that cluster-level failover is a feature of Pulsar rather than the Java client, so I think this part needs to be moved to another place.

### What is your suggestion?

I think we should move the introduction of `cluster-level failover` to the next chapter of [Geo Replication](https://pulsar.apache.org/docs/next/concepts-replication), and just give code snippets in client library pages (if supported).

cc @tisonkun @Anonymitaet @momo-jun @codelipenghui 

### Any reference?

https://pulsar.apache.org/docs/next/client-libraries-java#cluster-level-failover

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by MarvinCai** [comment]
though, this feature is only available in Java client for now: https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914

**Comment by labuladong** [comment]
> though, this feature is only available in Java client for now, see client feature matrix: https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914

Thanks for pointing out that, but I think moving the chapter is better. Reasons:

1. Cluster-level failover is a concept based on Geo replacation rather than a feature of the client.
2. Advanced features shouldn't be at the beginning of documentation.

We can emphasize this feature is only ready for the Java client yet, and add usage examples at the end of the Java client doc.

**Comment by Anonymitaet** [comment]
@labuladong thanks for raising this up! That’s a good point!

Just my two cents:

☘️☘️☘️ **1. Content mapping**

[Pulsar doc IA](https://docs.google.com/spreadsheets/d/1Zl7OUlh4McGOgkeePWP46HqMDEyG5GF8k0B3C5D5T7w/edit#gid=958558547) in being redesigned. Specific guides are being created for different roles:

- Beginners
- Developers
- Operators
- Contributors

Should the [existing content of cluster-level failover](https://pulsar.apache.org/docs/next/client-libraries-java/#cluster-level-failover) be split for operators and developers? See the table below.

☘️☘️☘️ **2. Content audit**

2.1 Instead of consolidating all content into the Java client guide (current situation), consider:
- Move `concept` and `reference` content to other places (make them independent topics + see 2.2)
- Keep "task-Java-related" content in Java client docs

Current content | Category| Changes to be made| Primary audience
---|---|---|---|
[Concept of cluster-leve failover](https://pulsar.apache.org/docs/next/client-libraries-java/#concept-of-cluster-level-failover)l  | Concept | Move | Operator
[Why use cluster-level failover?](https://pulsar.apache.org/docs/next/client-libraries-java/#why-use-cluster-level-failover)|Refrerence | Move | Operator
[When to use cluster-level failover?](https://pulsar.apache.org/docs/next/client-libraries-java/#when-to-use-cluster-level-failover) | Reference | Move | Operator
[When cluster-level failover is triggered?](https://pulsar.apache.org/docs/next/client-libraries-java/#when-cluster-level-failover-is-triggered) | Reference |Move | Operator
[Why does cluster-level failover fail?](https://pulsar.apache.org/docs/next/client-libraries-java/#why-does-cluster-level-failover-fail) | Reference |Move | Operator
[What are the limitations of cluster-level failover?](https://pulsar.apache.org/docs/next/client-libraries-java/#what-are-the-limitations-of-cluster-level-failover) | Reference |Move | Operator
[What are the relationships between cluster-level failover and geo-replication?](https://pulsar.apache.org/docs/next/client-libraries-java/#what-are-the-limitations-of-cluster-level-failover) | Reference |Move | Operator
[How to use cluster-level failover ](https://pulsar.apache.org/docs/next/client-libraries-java/#how-to-use-cluster-level-failover) | Task | Keep it in Java client guide | Operator
[How does cluster-level failover work?](https://pulsar.apache.org/docs/next/client-libraries-java/#how-to-use-cluster-level-failover)| Reference |Move | Developer? <br><br> Unsure about this since this part seems not quite "deeply technical"? Should operators be the primary audience?


2.2 `cluster-level failover` belongs to `fault tolerance`:
- Should we create an independent guide called `fault tolerance` and locate `cluster-level failover` there?
- Are there any other missing content that should be added to the `Pulsar fault tolerance` guide?

🔹🔹🔹

Thoughts?  @D-2-Ed @DaveDuggins @momo-jun @hangc0276 Thank you!

**Comment by momo-jun** [comment]
@labuladong @Anonymitaet  I agree it's a quick win to move the concept/ref information to a new topic in parallel with [Geo-replication](https://pulsar.apache.org/docs/next/concepts-replication) and only keep the content with code snippets for how to configure the java client to use cluster-level failover.  Regarding 2.2., IMHO, cluster-level failover is an HA (`high availability`) solution while `fault tolerance` goes beyond that providing redundancy.

**Comment by hangc0276** [comment]
@labuladong @Anonymitaet Thanks for tuning the document. 
I support moving the  Concept and Reference category parts into the high availability section and placing it in parallel with Geo-replication. The Geo-replication part also belongs to the HA section.

**Comment by labuladong** [comment]
Thanks for your discussion. Seems that a document redesign is planned in [Pulsar doc IA](https://docs.google.com/spreadsheets/d/1Zl7OUlh4McGOgkeePWP46HqMDEyG5GF8k0B3C5D5T7w/edit#gid=958558547), so do I need pull a request to simplify the current Java doc? 

I plan to create a new chapter "Cluster-level failover" behind the [Geo Replication](https://pulsar.apache.org/docs/next/concepts-replication) chaptar and only keep code demos in Java doc.

**Comment by momo-jun** [comment]
@labuladong I think you can go ahead. The IA redesign is a long-term project with continuous improvements.

**Comment by D-2-Ed** [comment]
@Anonymitaet  @labuladong I love the quick win - at a high-level this makes good sense, but before making changes and moving content, please create the information set map. (By doing so, you will ensure the relationships between the existing content and new /. updated content will make sense to the user, and verifies the navigation path and learner paths.)

**Comment by D-2-Ed** [comment]
@momo-jun > I think you can go ahead. The IA redesign is a long-term project with continuous improvements.
I agree the overall IA work is a long-term project, but as we touch any content we should apply the best practices so we can make incremental improvements in keeping with the overall strategy.
