### ISSUE TITLE
[Bug] Failed to open ledger

### ISSUE THREAD

**Issue by Technoboy-** [apache/pulsar#17520]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

- Master branch.
- Branch-2.11.

### Minimal reproduce step

Run test `ReplicatorTest#testReplicationWithSchema` in the master branch.

The test could run success if revert #17414.

### What did you expect to see?

The test should pass

### What did you see instead?

The test fails with :
```
org.apache.pulsar.broker.service.schema.exceptions.SchemaException: Error while recovering ledger -  ledger=2 - operation=Failed to open ledger
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
```

The root cause come from reading bk
![image](https://user-images.githubusercontent.com/6297296/188886197-02e32737-2a5f-4143-b957-ea9c831f6065.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Technoboy-** [comment]
Need some help for this issue @zymap @horizonzy

**Comment by zymap** [comment]
I am taking a look

**Comment by zymap** [comment]
The root cause is [this PR ](https://github.com/apache/bookkeeper/pull/3383).

The problem is that we cannot call [await() ](https://github.com/apache/bookkeeper/blob/be7053b850a3ad53c09baeac15b01cabc8e9412a/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java#L139)from an IO thread, even if we don’t have the consolidation in place
if the socket buffer is full, that blocking call would cause a deadlock, also without the consolidate
the await() was added, under the assumption that all these calls were coming from a thread pool dedicated to read operations.

I will push a fix to bookkeeper side and create a new release for fixing this.

**Comment by zymap** [comment]
Fixed through this PR https://github.com/apache/bookkeeper/pull/3480

**Comment by tisonkun** [comment]
Closed as fixed.
