### ISSUE TITLE
[Doc] Inconsistent npm compatibility across multiple sites

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#17786]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The npm compatibility for Node clients is inconsistent on multiple sites.

- https://github.com/apache/pulsar-client-node
   <img width="813" alt="image" src="https://user-images.githubusercontent.com/60642177/191409510-fa9f6930-b0e3-4c54-88f6-558ca0950c14.png">

- https://www.npmjs.com/package/pulsar-client
    <img width="734" alt="image" src="https://user-images.githubusercontent.com/60642177/191462363-65a92d5c-7aba-4f05-9c7a-6806d11db007.png">

- https://pulsar.apache.org/docs/client-libraries-node
   <img width="682" alt="image" src="https://user-images.githubusercontent.com/60642177/191409627-8093344b-f9b2-40ef-b7d7-b029546eb8ad.png">

### What is your suggestion?

1. Enable a single source for the shared information, and keep it up-to-date.
2. Link to the single source in other places.

Since the `README.md` file on https://github.com/apache/pulsar-client-node has the highest maintenance possibility and possibly the highest visibility as well, I suggest it is used as the single source.

@tisonkun @labuladong @Anonymitaet any thoughts?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Generally speaking, it's not about a single source of truth because here we don't have a reasonable single source.

* The difference between README.md and npm.js is due to that the latest version isn't uploaded to npm.js. npm.js displays README.md of uploaded artifacts.
* The difference between the doc site and the other two is due to...we don't update it :)

Actually, pulsar-client-node doesn't have a coupled release cycle with Pulsar main repo thus it's vague what version of node client should be attached with a certain versioned Pulsar doc.

The best solution is that pulsar-client-node has its own doc and we simply redirect to there - only retain few examples to get started with the client on Pulsar doc site and specify a certain version instead of trying to keep up-to-date.

cc the maintainers: @BewareMyPower @massakam @tuteng @hrsakai

**Comment by hrsakai** [comment]
I changed the compatibility table of [the pulsar document](https://pulsar.apache.org/docs/client-libraries-node/) to a link in https://github.com/apache/pulsar/pull/17935 .
