### ISSUE TITLE
[Doc] Update the release process about how to release C++ and Python client

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17918]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

After https://github.com/apache/pulsar/issues/17724 moves pulsar-client-cpp and pulsar-client-python to new repository, the original release process is no longer valid.

### What is your suggestion?

cc @merlimat @BewareMyPower @shibd @RobertIndie 

IIRC these two clients have their own release cycle, thus the issue here can be simply to remove the related sections in the current release process and then write the new one in each repo.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @merlimat @BewareMyPower 

Currently (2.8.4), even though C++ and Python are moved out of the main Pulsar repo, their release notes are still together with the Pulsar core.

- [Pulsar 2.8.4 release page](https://github.com/apache/pulsar/releases)

<img width="774" alt="image" src="https://user-images.githubusercontent.com/50226895/194842326-db617638-cf20-427d-9f2b-ae208db2a07c.png">

In the future, will the release notes of C++ and Python be in their repos and not bundled in the main Pulsar repo? Just like Go, C#, and Node.js?

- [apache/pulsar-client-cpp](https://github.com/apache/pulsar-client-cpp)

<img width="1536" alt="image" src="https://user-images.githubusercontent.com/50226895/194839848-67aae4eb-c9b7-4f42-92c9-62a594c72857.png">

- [apache/pulsar-client-go](https://github.com/apache/pulsar-client-go)

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/50226895/194840769-b8052edb-cef6-4ca1-999b-989f57ba85c7.png">

Thanks for your answer!

🔹🔹🔹

More context:

I ask this because we (@SignorMercurio @urfreespace) are implementing https://github.com/apache/pulsar/discussions/17310 

We need to change the workflow if the source truth of release notes is changed.

**Comment by tisonkun** [comment]
IIRC @BewareMyPower is going to update the C++ release process after 3.1.0 released. @BewareMyPower could you create a corresponding subtask in https://github.com/apache/pulsar-client-cpp?

**Comment by BewareMyPower** [comment]
Created: https://github.com/apache/pulsar-client-cpp/issues/123

**Comment by tisonkun** [comment]
@BewareMyPower @RobertIndie @shibd 

For the C++ client, we have https://github.com/apache/pulsar-client-cpp/wiki/Committer-Release-Guide now. What about the Python client?

**Comment by BewareMyPower** [comment]
@tisonkun I will write the process after the Python client 3.0.0 is out.

**Comment by tisonkun** [comment]
@BewareMyPower Thank you! If you'd like to create it in the https://github.com/apache/pulsar-client-python repo, can you open an issue there and let's close this as superseded by dedicated issues?

**Comment by BewareMyPower** [comment]
@tisonkun It's opened now: https://github.com/apache/pulsar-client-python/issues/64

**Comment by tisonkun** [comment]
Closed as superseded by:

* C++: https://github.com/apache/pulsar-client-cpp/issues/123
* Python: https://github.com/apache/pulsar-client-python/issues/64
