### ISSUE TITLE
[Doc] Missing the doc about how to authenticate a Kafka cluster using Kafka connectors

### ISSUE THREAD

**Issue by momo-jun** [apache/pulsar#17977]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

The issue was reported as below:

> I've been looking at the Pulsar Kafka connectors and noticed that there is no mention in the [source connector documentation](https://github.com/apache/pulsar/blob/master/site2/docs/io-kafka-source.md) about how to authenticate with a Kafka cluster (I couldn't find anything in the code either).

### What is your suggestion?

Add the documentation for https://github.com/apache/pulsar/pull/13095 to fill the content gap.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@momo-jun Thanks! The technical inputs can be fetched from https://github.com/apache/pulsar/pull/13095/files#diff-3fc217b425487539188b871310962802bf0d2350590e6935d7e6c64447f1274a

Hi @Shoothzj since you're the author of https://github.com/apache/pulsar/pull/13095, could you please help review the doc PR later?

cc @SignorMercurio another case that we need to update the connector conf table manually. This kind of doc is easy to miss.
