### ISSUE TITLE
[Doc] New references pages 404

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#17996]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

* https://pulsar.apache.org/reference/

... and if you try to jump to other versions:

* https://pulsar.apache.org/2.9.0/reference/

If you manually correct it to `https://pulsar.apache.org/reference/2.9.0`:

* https://pulsar.apache.org/reference/2.9.0

All the results above are out of expection.

### What is your suggestion?

Fix 404 and unrenderred pages.

### Any reference?

cc @Anonymitaet @urfreespace @momo-jun 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@SignorMercurio 
- The reference page is 404 
- The changes of this PR https://github.com/apache/pulsar-site/pull/246 are not shown on the website. 

Are they caused by website build failure?  
https://github.com/apache/pulsar-site/actions/workflows/ci-pulsar-website-next-build.yaml
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/50226895/195048694-61992ffb-648d-46dc-9afc-0de258640e5d.png">

**Comment by tisonkun** [comment]
> Are they caused by website build failure?

You may notice that the latest build succeeded but these pages still seem not found.

**Comment by SignorMercurio** [comment]
@Anonymitaet I'll investigate the reference 404 issue, but the changes of apache/pulsar-site#246 have already taken effect.
