### ISSUE TITLE
[Doc] Unify different styles in capitalizing strategy

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#18636]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

@momo-jun @Anonymitaet @DaveDuggins I noticed that we have different style in capitalizing strategy:

* Pulsar Configuration
* Pulsar metrics
* Geo Replication
* Cluster-level failover

What is the expected one? 

### What is your suggestion?

Decide one preference and align all references.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @tisonkun thanks for raising this up!

I believe all the examples you listed above should be in lower cases because:

- Most of them are in lower cases in the current docs, for example, 
<img width="1960" alt="image" src="https://user-images.githubusercontent.com/50226895/204177741-d91f61e3-26db-4d05-b919-17dda40ec683.png">

- Keeping them all in lower cases reduces maintenance cost.

**Comment by momo-jun** [comment]
According to the [Pulsar writing style guide](https://docs.google.com/document/d/1lc5j4RtuLIzlEYCBo97AC8-U_3Erzs_lxpkDuseU0n4/edit#heading=h.whzx4q25s26e), we use sentence-style capitalization with predominantly lowercase. We can correct these unaligned occurrences when touching them.

**Comment by tisonkun** [comment]
Thanks! I'm closing this issue as answered. Pending to port the writing style guide in the contribution guide in these two weeks.
