### ISSUE TITLE
[Bug] The search function on Pulsar home page does not work properly

### ISSUE THREAD

**Issue by jennifer88huang** [apache/pulsar#18687]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

V2.10.x

### Minimal reproduce step

When I search some keyword on [Pulsar home](https://pulsar.apache.org/docs/admin-api-tenants/#update) page, and does not get the expected result.
1. Enter a keyword in the search box, and click any item from the search list
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/95325635/204765766-42b93532-bed3-4489-9d72-c8f997e7b607.png">
2. The "Page not found" prompts out.
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/95325635/204765957-d1dbe24b-ca83-43b4-9a96-176c2984732f.png">

### What did you expect to see?

Navigate to the target page I've clicked.

### What did you see instead?

"Page not found" error
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/95325635/204766122-273ec016-1808-4026-9e5b-9d144851a74b.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment]
+1. Try to refresh the `not found` page, then it will work.

I notice that https://pulsar.apache.org/docs/admin-api-tenants/#update doesn't work but https://pulsar.apache.org/docs/2.10.x/admin-api-tenants/#update works. 

Any ideas about this bug? @urfreespace @tisonkun

**Comment by tisonkun** [comment]
Closed. After index regenerated, it should be fixed now.

**Comment by tisonkun** [comment]
Here is the long version of the reason:

We previously served the latest version docs under /docs/ . And Algolia indexed those pages.

In https://github.com/apache/pulsar-site/pull/288 we served the latest version docs under its exact version said /docs/2.10.x/ and set up client-side redirections for the previous URL path. Algolia doesn’t update the index for this change.

So, when you search under 2.10.x now, you will get the result of /docs/ , and due to Docu’s routing mechanism, jumping to such a page doesn’t cause a page to reload, so the client-side redirections do not work.

It’s always a challenge to work with a full-encapsulated framework/service, worse if their combination :)
