### ISSUE TITLE
Generate swagger files on sync and manually

### ISSUE THREAD

**Issue by tisonkun** [apache/pulsar#18724]

**Comment by tisonkun** [comment]
@Jason918 @michaeljmarshall how do we currently use swagger files?

I'm going to remove files under the main repo and only generate on sync or manually (on release) in the site repo.

It seems that we generate swagger files for each minor release and I wonder why. (BTW, some site logic depends on `restApiVersions.json` to resolve real versions so if we want to change the strategy, it can take extra effort.)

**Comment by tisonkun** [comment]
I'm going to add a pytool to generate swagger files and move the sources there.

**Comment by michaeljmarshall** [comment]
@tisonkun - sorry for the delay. I support moving the generated files to the pulsar-site repo.

> how do we currently use swagger files?

Some people use the swagger files to generate clients. This is something that @visortelle has worked on and has contributed fixes to our annotations to make the generated clients work better. Here is a sample third party generated client: https://github.com/tealtools/pulsar-admin-client-js.

Since APIs can change slightly for each minor version, even with things like improved annotations, I personally think it makes sense to generate the swagger files for every release.
