### ISSUE TITLE
[Doc] management API docs misleading and unclear re: namespace properties 

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#19466]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Two issues:

~1. The API docs for [`https://pulsar.apache.org/admin/v2/namespaces/{tenant}/{namespace}/properties`](Get key value pair properties for a given namespace.
) say:~

~But that's not quite what that endpoint does; that endpoint gets the *entire namespace config*, including properties and everything else. Which is very useful, but unrelated to the "properties" APIs listed below that.~

**Update: this is invalid and the result of user error. The second issue is real though.**

 2. The API docs for [namespace property deletion](https://pulsar.apache.org/admin-rest-api/#operation/removeProperty) say:
 
 > Get property value for a given key on a namespace.

This is inaccurate; that API deletes things, and does not get them.

### What is your suggestion?

1. Update the docs for `/properties` to be clearer that it returns the entire namespace config including properties.
2. Update the description string for the properties-delete API to be accurate.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
@zbentley Thanks for raising this up! Can you check the following questions from the technical side? So that we know how to update the docs. Thank you!

### Q1

Do you mean adding explanations like below?
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/50226895/217995927-4f439a4e-6f10-41c0-a2b3-1df9eebdae59.png">

### Q2

2.1 green box: [change "Get" to "Delete"](https://github.com/apache/pulsar/blob/b969fe5e56cc768632e52e9534a1e94b75c29be1/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java#L2602)?

2.2 red box: is the content correct? (currently they are almost same to [Get property value for a given key on a namespace](https://github.com/apache/pulsar/blob/b969fe5e56cc768632e52e9534a1e94b75c29be1/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java#L2588)

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/50226895/217996601-1b4d85b9-566a-458c-8beb-4398802efeee.png">

**Comment by zbentley** [comment]
Thanks @Anonymitaet! 

Q1: I deleted that from the initial request, as it was user error. That API endpoint works as currently described, sorry for the confusion.

Q2.1: The box is already the right (deletion) color.

Q2.2: The content is not correct. Deletion removes a property (it doesn't "Get property value") from the map and returns the string key property name. The docs should indicate that.

**Comment by Anonymitaet** [comment]
@zbentley Thanks for your explanations! Double-check:

From line 2601 to 2611:
1. Only line 2602 should be changed to "Remove a property value from a map and return a string key property name"?
2. Rest lines remain unchanged?

**Comment by zbentley** [comment]
Yep, that is accurate! Thank you!

**Comment by Anonymitaet** [comment]
Hi @horizonzy can you please double-check this change from the technical perspective? Thank you!

**Comment by horizonzy** [comment]
We should modify both the code and the doc.

**Comment by Anonymitaet** [comment]
@horizonzy REST API doc is generated from this code automatically, so modifying code (value descriptions) means updating docs as well.

> We should modify both the code and the doc.

**Comment by horizonzy** [comment]
Fine.
