### ISSUE TITLE
[Doc] Document PULSAR_CLIENT_CONF env variable. Missing TLS-related CLI arguments

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#19492]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

I need to be able to work with several Pulsar instances using pulsar-admin.
For each Pulsar instance, I have a different TLS configuration.

It's unclear from the docs or CLI help, what I should do in this case.

As I see, it's documented for pulsar-perf, but not for pulsar-admin and pulsar-client.

<img width="903" alt="Screenshot 2023-02-11 at 9 32 49 AM" src="https://user-images.githubusercontent.com/9302460/218248647-22b27073-bdfb-4bb8-90e1-a22962a9e864.png">

### What is your suggestion?

- Add the documentation on the docs site.
- Add the documentation to pulsar-admin, pulsar-client and pulsar-perf.
- It would be nice to have a `--config-file` CLI argument instead of an env variable. Even better to expose missing configuration parameters as CLI arguments.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Anonymitaet** [comment]
Hi @visortelle 

> Add the documentation on the docs site.

Q1: Do you mean adding instructions/examples on how to use these 4 environment variables?

 > Add the documentation to pulsar-admin, pulsar-client and pulsar-perf.

Q2: now we have docs for pulsar-perf as below
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/50226895/218357867-cfdf7d6f-cdb8-47e7-8e45-714109800ca7.png">

Do you mean adding similar content to pulsar-admin and pulsar-client?
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/50226895/218358027-be28e9e2-1802-469f-b00f-2bbbec26294f.png">

**Comment by visortelle** [comment]
Hi @Anonymitaet 

---
`pulsar-perf` CLI tool has the `Environment variables` help section in a terminal.
This section is missing in the `pulsar-admin` and `pulsar-client` CLI tools help.

Same for the docs site.

---
Regarding instructions/examples - not sure that it's necessary. 

I'd add links to the according files and improve its code comments if necessary.

`PULSAR_CLIENT_CONF`:
 See https://github.com/apache/pulsar/blob/master/conf/client.conf for details.

`PULSAR_LOG_CONF`:
See https://github.com/apache/pulsar/blob/master/conf/log4j2.yaml for details.

**Comment by Anonymitaet** [comment]
@visortelle Thanks! This issue contains two types of improvements:

### Doc improvements

☘️ **TO-DOs**
Add the `environment variables` section to the following pages.
- Reference site - [`pulsar-perf` home page](https://pulsar.apache.org/reference/#/next/pulsar-perf/)
- Reference site - [`pulsar-admin` home page](https://pulsar.apache.org/reference/#/next/pulsar-admin/)
- Reference site - [`pulsar-client` home page](https://pulsar.apache.org/reference/#/next/pulsar-client/)

☘️ **Reasons**
This section is shown on 2.10.x and earlier markdown docs (e.g., https://pulsar.apache.org/docs/2.10.x/reference-cli-tools/#pulsar-perf) but not available on 2.11.x and later Reference site. 

Since the reference pages of `pulsar-perf`, `pulsar-admin`, and `pulsar-client` are [generated automatically](https://pulsar.apache.org/contribute/document-contribution/#update-command-line-tool-docs), we can add the `environment variables` section to the their homepage as a temporary workaround. We can optimize it once we find better solutions.

@momo-jun @DaveDuggins @D-2-Ed WDYT?

### Code improvements

I've double-checked and tested the current code behavior and then recorded it in https://github.com/apache/pulsar/issues/19526. Feel free to correct me if I'm inaccurate, thank you!

**Comment by shy-share** [comment]
> `PULSAR_CLIENT_CONF`: See https://github.com/apache/pulsar/blob/master/conf/client.conf for details.

@visortelle  That means the environment variable of pulsar-client is all the values in this file right?
