### ISSUE TITLE
[Doc] color code 

### ISSUE THREAD

**Issue by anguillanneuf** [apache/pulsar#20036]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

![Screenshot 2023-04-06 at 3 44 57 PM](https://user-images.githubusercontent.com/9518298/230507366-10ede333-d578-4bb1-9a42-6767b1ec891d.png)

The color codes don't corresponds to the diagram. 

### What is your suggestion?

Either re-do the diagram using the color codes in the texts or remove the color-coded texts.

### Any reference?

https://pulsar.apache.org/docs/2.11.x/concepts-messaging/#message-retention-and-expiry

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Hi @anguillanneuf! Thanks for reporting this issue.

Since you click the "I'm willing to submit a PR!" box, I'll double-check that if you'll draw the diagram. This is not quite easy for software developers, though.

**Comment by anguillanneuf** [comment]
I unchecked the box and won't be submitting a fix @tisonkun. Thanks for the quick response!

**Comment by Anonymitaet** [comment]
Hi @momo-jun I've checked the commit history and found that seems you're the author of this change? If so, can you give us more context?

**Comment by momo-jun** [comment]
@Anonymitaet I've no idea about this one and didn't notice this image change. My commit related to message retention was about the [cookbook](https://github.com/apache/pulsar/pull/14546) topic, not the concept one.

I'm not sure about the motivation to change the images (maybe for style alignment ?) in 2.11 docs, but it did break the consistency between the content and the image. Just FYI, I think the easiest way to resolve this inconsistency can be:
* Revert the original images used in 2.10.x
* Remove the hard-coded color code in the MD file (maybe better).

**Comment by Anonymitaet** [comment]
@momo-jun OK, thanks! 

Updating the color text to black text is a better way since black text and the image in NEXT and 2.11.x matches our current design style (while the image in 2.10.x does not) 

- [Image in NEXT and 2.11.x ](https://pulsar.apache.org/docs/2.11.x/concepts-messaging/)
![image](https://user-images.githubusercontent.com/50226895/230844272-043a0a3f-bdcc-4449-8c42-0602303eebf1.png)

- [Image in 2.10.x](https://pulsar.apache.org/docs/2.10.x/concepts-messaging/)
![image](https://user-images.githubusercontent.com/50226895/230844491-a3bb89c2-a2e7-4085-af37-d010524ad76d.png)
