### ISSUE TITLE
Add sdkman support

### ISSUE THREAD

**Issue by nodece** [apache/pulsar#22298]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

https://sdkman.io/ is a good tool for managing our Java, and when using a shell, it automatically loads(sdkman_auto_env=true) the configured version of the programming language.

1. Add `.sdkmanrc` to project root
```
java=17.0.10-amzn
```

2. Load config
```
$ sdk env

Using java version 17.0.10-amzn in this shell.
```

This can maintain JDK version consistency between the development/build environment and the CI environment.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
I use this type of setup with Pulsar. However, I don't encourage to add the files to the repository. The reason for this is that having a fixed JDK version in `.sdkmanrc` isn't very useful. 

I'd recommend adding this to developer documentation instead of adding the `.sdkmanrc` files to the GitHub repository.

I have a global `~/.gitignore_global` file with `.sdkmanrc` in there so that it doesn't get added to git.
`~/.gitignore_global` has been registered with `git config --global core.excludesfile ~/.gitignore_global`.

**Comment by nodece** [comment]
> I use this type of setup with Pulsar. However, I don't encourage to add the files to the repository. The reason for this is that having a fixed JDK version in `.sdkmanrc` isn't very useful.

I prefer to use only major version like `java-17 item`, but sdkman requires a full version, which is unfriendly.

> I'd recommend adding this to developer documentation instead of adding the .sdkmanrc files to the GitHub repository. 

This is a good idea, but I'm concerned that developers don't read this documentation. Out of the box breaks the configuration of users who have already configured sdkman. 

Let's do this in the development documentation.
