### ISSUE TITLE
Wait for consumer “creation” to be completed before start delivering

### ISSUE THREAD

**Issue by zubchenok** [apache/pulsar#2298]
In Java client if you create a consumer in async way and set MessageListener, 
in rare cases MessageListener will be called before you get a callback about created consumer. 

It isn't intuitively expected.

I suggest to wait until the consumer's callback is called before starting deliver messages via listener callback.

**Pulsar version**: 1.22.1

**Comment by merlimat** [comment]
@zubchenok While I have seen that this issue might happen with multi-topic subscribe (which is in 2.x anyway), I don't see it happening when subscribing to either single or partitioned topics. 

At https://github.com/apache/incubator-pulsar/blob/c9a369936af3b3ecc663b86ae959a3fbfa627aca/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L586-589 is where first the future is completed and then, the client will send "permits" to have broker to start message delivery. 

Since you mentioned `subscribeAsync()`, are you processing the result of that future from same thread or spawing to a different thread? (eg: `thenAccept()` vs `thenAcceptAsync()`. Then 2nd will use a background thread to execute, so there would be no ordering of when it will be invoked.

**Comment by codelipenghui** [comment]
@zubchenok I will close this first, if you have any update or issues related to this issue, feel free to reopen it.
