### ISSUE TITLE
[Bug] org.apache.pulsar:pulsar-package-bookkeeper-storage:jar:3.4.0-SNAPSHOT was not found

### ISSUE THREAD

**Issue by four1er** [apache/pulsar#23096]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

OS: Mac OS 14.5 M1 Pro
Java version: jdk-17.0.4.1
Pulsar version: master(47d35a0af8ef72062288866f0c875312b5684906)

### Minimal reproduce step

Click the "Generate Sources and Update Folders For All Projects" button in the  Maven UI toolbar.
<img width="463" alt="image" src="https://github.com/user-attachments/assets/f332d58e-3126-4025-83b2-6e3979520098">

### What did you expect to see?

Generate Source success.
<img width="364" alt="image" src="https://github.com/user-attachments/assets/b00b16a3-9b1d-47f1-9407-ca1ecbd51b08">

### What did you see instead?

org.apache.pulsar:pulsar-package-bookkeeper-storage:jar:3.4.0-SNAPSHOT was not found.

### Anything else?

This is because the pom.xml use 3.4.0 as the dependency version, but the newest version is 2.10.7.2-SNAPSHOT-86382c9.
```
      <dependency>
        <groupId>org.apache.pulsar</groupId>
        <artifactId>pulsar-package-bookkeeper-storage</artifactId>
        <version>${project.version}</version>
      </dependency>
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
This seems to be a reported about an issue with IntelliJ, however you didn't mention the IntelliJ version.
I'd recommend ensuring that you are using the latest IntelliJ version with updates since there have been issues in the past where the user has been using an outdated version of IntelliJ.

If that doesn't resolve the issue, I believe that this type of issues can be resolved by running `mvn clean install -DskipTests`. (for faster execution, I typically run `mvn -Pcore-modules,-main -T 1C clean install -DskipTests -Dspotbugs.skip=true -DnarPluginPhase=none`)

We have IDE instructions at https://pulsar.apache.org/contribute/setup-ide/ . It's possible that the instructions are slightly outdated.

**Comment by lhotari** [comment]
Closing this issue since there hasn't been any feedback from the reporter.
