### ISSUE TITLE
[Bug] Upgrade shaded netty for CVE-2024-47535

### ISSUE THREAD

**Issue by gergelyfabian** [apache/pulsar#23597]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

pulsar-client 3.3.2

### Minimal reproduce step

pulsar-client includes a shaded Netty (4.1.113.Final) that has a CVE: CVE-2024-47535.
4.1.115 includes a fix for the CVE.

### What did you expect to see?

Pulsar client containing a CVE-free shaded Netty.

### What did you see instead?

CVEs detected when using pulsar-client as a dependency.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by gergelyfabian** [comment]
Duplicate of #23596

**Comment by lhotari** [comment]
@gergelyfabian Just curious to know about your vulnerability handling requirements.

In this case, CVE-2024-47535 isn't a real threat for Pulsar or Pulsar client users due to the nature of the vulnerability where malicious users would have to have write access to the local filesystem to cause an out-of-memory issue for an application using Netty. The probability of this happening in reality is close to 0. That's why it's safe to add an exemption for CVE-2024-47535 in your vulnerability management and ignore it.

I'm aware that some organizations have policies where a CVE with severity of 7.0 or higher must be addressed within a certain time frame (for example, in 30 days), and the exemption process is so heavy that it's easier to simply update the dependencies and address it that way. In Apache Pulsar, we will update dependencies whenever there's a CVE and upgrading doesn't cause compatibility issues or breaking changes for users.
