### ISSUE TITLE
[Feature request] Namespace/topic rack affinity

### ISSUE THREAD

**Issue by cbornet** [apache/pulsar#3104]
When deploying a single cluster over multiple AZ/regions, one of the main drawbacks is the cross-dc bandwidth used by the producers/consumers.
So it would be handy to be able to configure rack affinity either of namespaces or topics so that the brokers are chosen in priority on the preferred rack with fallback on other racks if no brokers are available on the preferred rack.

**Comment by merlimat** [comment]
@cbornet I think this could be achieved even today (this time for real :) ).

There is a concept of "namespace isolation". It's not super-well documented, but it's a feature that was there since the beginning. http://pulsar.apache.org/docs/en/pulsar-admin.html#ns-isolation-policy

The idea is that you can isolate namespaces to a subset of brokers and these brokers will be dedicated to these namespaces.

Then, there is the concept of primary and secondary broker sets. The primary set is where you want the topics for that namespaces to be placed by preference. If no broker from primary set is available, then topics will spill over to secondary.

One could configure "primary" to be the brokers from the preferred DC and secondary to `.*`

**Comment by ivankelly** [comment]
@merlimat could you followup?

**Comment by cbornet** [comment]
Namespace isolation works fine. What's missing is a little more doc on how to use it. Do you want to close the issue or keep it open for the doc part ?

**Comment by eolivelli** [comment]
it looks like that ZkIsolatedBookieEnsemblePlacementPolicy is not activated.

On current master it kicks in only in case of the presence of configuration of a bookieAffinityGroup
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1193

**Comment by Anonymitaet** [comment]
We @codelipenghui are working on this doc.
