### ISSUE TITLE
Function option --subscription-type does not work

### ISSUE THREAD

**Issue by ngjaying** [apache/pulsar#3224]
The option is documented at https://pulsar.apache.org/docs/en/pulsar-admin/#create-1, but it is actually an invalid option. I find it was once supported in the CmdFunctions.java source code but was deleted later. Will it be supported again?

#### System configuration
**Pulsar version**: 2.2.0

**Comment by sijie** [comment]
@ngjaying : 

the documentation is probably out of date. the subscription-type was removed since 2.1.0 release. instead you should use processing guarantees or retainOrdering, so the pulsar functions would choose the right subscription type for processing guarantees.

see details in #1880

@jerrypeng : can you help update the documentation about this tool?

**Comment by jerrypeng** [comment]
@ngjaying there is really no point for a function that uses an exclusive subscription since the failover subscription can be viewed as a exclusive subscriptions with fault tolerance.

**Comment by sijie** [comment]
@ngjaying it is an interesting use case. However I think the key requirement here is not  supporting exclusive subscription.

> For exclusive subscription, I think each function instance can have a different subscription name so that all function instances can read from the topic.

I think your key requirement is each function instance would have a different subscription name for that topic. in the case, it doesn't really matter it is exclusive, failover or shared subscription. because this instance is reading the entire topic.

Can you check if I understand your requirement correctly?

**Comment by ngjaying** [comment]
@sijie This is exactly my requirement, thanks for summarizing it.

**Comment by Jennifer88huang** [comment]
Does Pulsar support the requirement from @ngjaying now?

**Comment by geomagilles** [comment]
also, you can not obtain a key-shared subscription currently with the current method. (related to #3208 and #6527)
