### ISSUE TITLE
[Question]How to configure log level for pulsar functions

### ISSUE THREAD

**Issue by ngjaying** [apache/pulsar#3259]
This may be a dumb question but I cannot find how to do.  
```
org.slf4j.Logger logger = context.getLogger();
logger.debug("debug message");
```
I cannot find how to enable the debug message. I try to modify conf/log4j2.yaml to change all INFO to DEBUG, but that seems only affect broker log.

#### System configuration
**Pulsar version**: 2.2.0

**Comment by sijie** [comment]
Currently there is no programming way to configure debug level on per function basis. If you are using Process runtime, it is no simple way to change the log level. because the log4j settings is controlled by this log4j2.yml file (https://github.com/apache/pulsar/blob/master/pulsar-functions/runtime/src/main/resources/java_instance_log4j2.yml) which is packaged into the java instance runner. 

For production usage, I would suggest logging important information at info level. For development purpose, you can use local-run to run your function to debug things. local-run will use `conf/log4j2.yml` file for logging configuration.

If you indeed have use cases to change log level per function basis, we can think of how to improve it.

**Comment by sijie** [comment]
Closed the question since the question is answered
