### ISSUE TITLE
Pulsar IO connector for Flume source

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3275]
This requirements has been asked from several people. 
This is trying to track this requirement: use [flume](https://github.com/apache/) as source of data.

**Comment by tuteng** [comment]
Is this feature more suitable for submission to the flume repository? As a sink of flume

**Comment by sijie** [comment]
@tuteng : 

I think there two ways to do connectors:

1) adding a connector in Flume repo, which implements Flume's plugin interfaces. 
2) adding a pulsar connector that receives data from flume or to flume, which implements Pulsar's connector interfaces.

from functionalities perspective, both 1) and 2) are doing the same thing. the differences will be - who is running the "connecting" logic. 

for 1), it is more suitable for adding the connector to flume's repository.
for 2), pulsar's main repo is probably the best location. 

either 1) or 2) can also be a separate github repo hosting at your github account, and if you want to maintain them as the versions evolve.

I think the issue here falls into the second category.

**Comment by tuteng** [comment]
For the second catecory.
Sending data to flume is relatively easy and can be implemented using both flume-ng-client and flume-ng-sdk.
However, I have not found a better way to receive data from flume. Flume officials have implemented various sink to send out data.For example https://github.com/apache/flume/tree/trunk/flume-ng-sdk

**Comment by sijie** [comment]
@tuteng your understanding is correct. for the second category, there is no easy way to receive data from flume.  I think @ambition119 or @jiazhai is looking into this. they might have better context than me regarding whether there is any approach to receive data from flume.

**Comment by ambition119** [comment]
@jiazhai @sijie I just try FlumeAvroSink, not try FlumeSource like spark offer FlumeUtils.  @tuteng if you interest，you can commit this issue.  tks

**Comment by jiazhai** [comment]
@ambition119 Thanks for the comments. You could open the issue for FlumeAvroSink, and assign it to yourself. 
@tuteng Would you like to contribute to this issue?

**Comment by tuteng** [comment]
Okay, thanks.

**Comment by ambition119** [comment]
@tuteng  FlumeSink I ok.  How is your work going?
![image](https://user-images.githubusercontent.com/20353043/51980299-9b5bf700-24ca-11e9-93a7-da21317622c5.png)

**Comment by tuteng** [comment]
@ambition119 Almost the tests have passed, and there are still some areas to be modified.But I import flume agent, source, sink, channel of flume need to be realized. I'm currently implementing sink of flume (source of pulsar). https://github.com/AmateurEvents/pulsar/tree/feature/support-flume/pulsar-io/flume/src/main

**Comment by ambition119** [comment]
> @ambition119 Almost the tests have passed, and there are still some areas to be modified.But I import flume agent. Source, sink, channel of flume need to be realized. I'm currently implementing sink of flume (source of pulsar). https://github.com/AmateurEvents/pulsar/tree/feature/support-flume/pulsar-io/flume/src/main

ok

**Comment by sijie** [comment]
The flume connectors are implemented at #3597
