### ISSUE TITLE
Broken KEYS link on https://pulsar.apache.org/download/

### ISSUE THREAD

**Issue by sebbASF** [apache/pulsar#3319]
The KEYS link still points to incubator

**Comment by merlimat** [comment]
@sebbASF I had this fixed few days ago in https://github.com/apache/pulsar/pull/3282 
The issue is that the website building job has been failing for a few days and not updating: https://builds.apache.org/job/pulsar-website-build/

**Comment by sebbASF** [comment]
The build error is:

cp: target '/pulsar/generated-site/content' is not a directory

should be easy enough to fix?

**Comment by merlimat** [comment]
Unfortunately not. That was actually due to an attempt to fix the build. 

Problem is we were still building the "old" website too as part of the build. The build happens in a Docker container with all the dependencies, though some Ruby dependencies are fetched at build time and, due to some changes in these dependencies, the old-site build script started failing. 

I tried to fix by just building the current website, but the above error is now coming. I'll get to it by tomorrow.

**Comment by merlimat** [comment]
The website build was finally fixed and the page is updated now with the right link.
