### ISSUE TITLE
support Pattern subscribe in kafka compat client

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#3733]
**Describe the bug**
Kafka wrapper not support pattern subscribe, in this [link](https://github.com/apache/pulsar/blob/master/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/consumer/PulsarKafkaConsumer.java#L292)

Since Pulsar now support Pattern type subscribe, we should add the support for this.

**Comment by liketic** [comment]
Hi @jiazhai , I'd like to work on this. I just want to know how can we get the partitions for those matched topics, which can be used to construct TopicPartition like ```subscribe(Collection<String> topics, ConsumerRebalanceListener callback)``` did. Could you please give me some hints ?

**Comment by sijie** [comment]
@liketic 

I am not sure you need to get the partitions. Because pulsar client already handles that. 

If you want to subscribe to a list of topics, you can do that in ConsumerBuilder to set a list of topics.

Hope this clarify your questions.

**Comment by jiazhai** [comment]
@liketic Thanks for take care this issue. Thanks @sijie for the clarification.
the original change for pulsar java client is in PR #1279
you could also reference #3256.

**Comment by liketic** [comment]
Thank you @jiazhai @sijie . The method ```subscribe``` https://github.com/apache/pulsar/blob/41b286dc0cc7b6ca3aa24acfccd53dfed547c0c5/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/consumer/PulsarKafkaConsumer.java#L215 

lists all partitions for each topic and create a ```TopicPartition``` instance for each pair of them, and update the member variables ```consumers``` and ```unpolledPartitions``` for later use.
What I mean is if we need to do the same things, try to get all topics matched the pattern and then get all partitions for each topic...  , which means we need a method to list all topics based on a regex in client.

Otherwise, what I can think of is something like:
```
    @Override
    public void subscribe(Pattern pattern, ConsumerRebalanceListener callback) {
        ConsumerBuilder<byte[]> consumerBuilder = PulsarConsumerKafkaConfig.getConsumerBuilder(client, properties);
        consumerBuilder.subscriptionType(SubscriptionType.Failover);
        consumerBuilder.messageListener(this);
        consumerBuilder.subscriptionName(groupId);
        consumerBuilder.topicsPattern(pattern);
        try {
            consumerBuilder.subscribe();
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }
```

**Comment by sijie** [comment]
@liketic 

I see your point now. if we don't care about notifying `ConsumerRebalanceListener`, then we can just use `#topicsPattern(pattern)`.

so I would suggest introducing a `TopicPartitionListener` in pulsar consumer to receive the partitions. so pulsar will manage notifying the topic partitions, instead of us doing this in kafka wrapper. so the implementation in kafka wrapper would be something like

```
    @Override
    public void subscribe(Pattern pattern, ConsumerRebalanceListener callback) {
        ConsumerBuilder<byte[]> consumerBuilder = PulsarConsumerKafkaConfig.getConsumerBuilder(client, properties);
        consumerBuilder.subscriptionType(SubscriptionType.Failover);
        consumerBuilder.messageListener(this);
        consumerBuilder.subscriptionName(groupId);
        consumerBuilder.topicsPattern(pattern);
        consumerBuilder.topicsListener(topicPartitions -> {
               callback.onPartitionsAssigned(topicPartitions);
        });
        try {
            consumerBuilder.subscribe();
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }
```

**Comment by fantapsody** [comment]
There seems to be a few problems in the current implementations of kafka compact clients, I'm not sure if they have been reported:
1. `KafkaConsumer` states its `subscribe` methods are not incremental, which means new subscriptions will replace the old ones. However, implementions in PulsarKafkaConsumer are not, and seem to create dangling consumers if re-subscribe to the same topics.
https://github.com/apache/kafka/blob/f698f3f8401845e0f73b104c0f96c54d2851b67a/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L957
https://github.com/apache/pulsar/blob/54b39e64f361a2ed5242259e04505bcfc66c1c8a/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/consumer/PulsarKafkaConsumer.java#L267
2. `ConsumerRebalanceListener.onPartitionsAssigned` should be called when the partition becomes active.
3. Methods in `PulsarKafkaConsumer` are not totally thread safe, although concurrent collections are used.

**Comment by fantapsody** [comment]
It seems several places in `PulsarKafkaConsumer` are affected In order to use `consumerBuilder.topicsPattern(pattern)` for subscription, like messageId/offset management/seeking/commit, consumer management, etc. And maybe we should also reimplement the multi-topic subscription using that provided by the underlying pulsar client? That may simplify the implementation as a whole, but need more work and tests than expected.
https://github.com/apache/pulsar/blob/54b39e64f361a2ed5242259e04505bcfc66c1c8a/pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/consumer/PulsarKafkaConsumer.java#L240

**Comment by sijie** [comment]
@fantapsody 


> And maybe we should also reimplement the multi-topic subscription using that provided by the underlying pulsar client? 

+1

**Comment by tisonkun** [comment]
The module is removed.

Closed as invalid. Perhaps it's something you can report to https://github.com/streamnative/kop.
