### ISSUE TITLE
How to configure the geo-replication we have two datacenters

### ISSUE THREAD

**Issue by gopalvd** [apache/pulsar#4334]
#### Expected behavior

Tell us what should happen

#### Actual behavior

Tell us what happens instead

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: 2.3.1

I am having some trouble in setting the geo-replication. I have two datancenters and i am succuessful in producing and consuming the messages in each data center individually and wanted to set up a geo-replication, where i am not able to understand what i have to pass the --allowed-clusters parameter in the command `pulsar-admin properties create my-tenant \
  --admin-roles my-admin-role \
  --allowed-clusters us-west,us-east,us-cent` in this example they gave us-west, east, cent but how these are different from the clusternames we gave while configuring. Again if i give the cluster names of both the DC's i am getting `Invalid cluster Id: <clustername>

I tried looking this document https://github.com/yahoo/pulsar/blob/master/docs/GeoReplication.md but getting 404 not found. Can anyone help on this?

**Comment by sijie** [comment]
@gopalvd 

You can checkout the geo documentation here: http://pulsar.apache.org/docs/en/administration-geo/

If you want to enable geo-replication, you need a global zookeeper. so both two data centers can share the same namespace policy (with the replicated clusters). I guess the exception you got is due to you don't configure the two clusters with a global zookeeper.

If you don't have a global zookeeper cluster, you can still do geo-replication. you just need to let each data center know how to communicate with the other data center. I have created a gist with a tutorial for geo-replication without a global zookeeper:

https://gist.github.com/sijie/79364497eaa349bf58d9fb760561f930

hope this helps!

**Comment by sijie** [comment]
@gopalvd does my last comment help?

**Comment by gopalvd** [comment]
Yes.. we were able to implement the geo-replication successfully and we are trying the security authentication now. We need to configure the TLS server for that. Working on that. But thanks alot for the help on the geo-replication.

**Comment by sijie** [comment]
@gopalvd Glad that your problem is resolved.

**Comment by one70six** [comment]
FYI, for those with TLS issues on Geo-Replication:
https://gist.github.com/sijie/79364497eaa349bf58d9fb760561f930#gistcomment-3149751
