### ISSUE TITLE
Where can I find the helm chart to deploy Pulsar SQL with HA?

### ISSUE THREAD

**Issue by vivekpd15** [apache/pulsar#4423]
Where can I find the helm chart to deploy Pulsar SQL with HA?

**Comment by sijie** [comment]
@vivekpd15 currently the documentation about this part is missing. 

However since Pulsar SQL is effectively Presto, you might be able to checkout presto documentation to setup HA for Pulsar SQL.

For example: https://coding-stream-of-consciousness.com/2018/12/29/presto-coordinator-high-availability-ha/

**Comment by vivekpd15** [comment]
@sijie Thanks for the info.

**Comment by Jennifer88huang** [comment]
I've checked Presto documentation, HA is not added anywhere at https://prestodb.io/docs/current/ .
Since Pulsar SQL uses Presto, and HA is actually not available in Presto (https://coding-stream-of-consciousness.com/2018/12/29/presto-coordinator-high-availability-ha/), we'd better not add setup info in Pulsar SQL doc. However, we can add a short paragraph on how to deploy Pulsar SQL with HA with the above link(this solution might change as time passes by) if this deployment is vital for most users.
Do you have any suggestion on the solution? @sijie @vivekpd15

**Comment by Jennifer88huang** [comment]
I've checked the latest prestosql https://prestosql.io/docs/current/, it does not support HA either.

**Comment by Jennifer88huang** [comment]
In the latest Presto release, HA is not mentioned either https://prestosql.io/Presto_SQL_on_Everything.pdf

**Comment by Jennifer88huang** [comment]
Since Presto does not support HA, I'll close this issue.
