### ISSUE TITLE
pulsar function update: reduce parallelism

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#4522]
**Describe the bug**
When using `bin/pulsar-admin function update` with option `--parallelism` doesn't work to reduce the parallelism.

**Comment by jerrypeng** [comment]
@KannarFr we have integration tests for this and I just tested this on latest master.  Reducing the parallelism is working as it should. 

Can you list the command you are trying to run and what happens when you run the command?  And what is your deployment environment like?  What version of Pulsar are you using?

**Comment by KannarFr** [comment]
@jerrypeng okay, all my bad it works.
