### ISSUE TITLE
[docs] Improve the structure of Pulsar Functions

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#4554]
**Is your feature request related to a problem? Please describe.**
I'm a little confused when searching information on Pulsar Functions. The content is scattered in different sections and does not integrate as a whole. Meanwhile, some information duplicates in *Overview* and other sections. It's a little bit frustrating to read the docs as a new user.

**Describe the solution you'd like**
I want to re-structure the architecture of Pulsar Functions as follows, so it will be easier to read and find information.
![image](https://user-images.githubusercontent.com/47805623/59657763-43513300-91d4-11e9-889b-bb1e1aeee09a.png)

If you have any suggestion on the new architecture, feel free to contact me.
If there is no issue with it, I'll update the content throughout.

**Comment by sijie** [comment]
@srkukarni @jerrypeng @jiazhai @wolfstudy @rdhabalia can you guys help review @Jennifer88huang 's proposal on improving the functions doc?

**Comment by Jennifer88huang** [comment]
Is there any suggestion on the proposal?

**Comment by jerrypeng** [comment]
@Jennifer88huang I would change:

1. Function Worker -> Deployment or Cluster Deployment?
Since first timers would even know what "Function worker" is.

2. Deploy -> Function Deployment? 
For more info on how to run functions.

While I am ok with having separate headings/pages for Java, Python, and Go functions, we can also have them together but just have different examples for different languages like:

https://spark.apache.org/docs/latest/quick-start.html

**Comment by Jennifer88huang** [comment]
> 1. Function Worker -> Deployment or Cluster Deployment?
>    Since first timers would even know what "Function worker" is.
@sijie Any thoughts on this?

> 2. Deploy -> Function Deployment?
>    For more info on how to run functions.
Sure, we can change it as "Function Deployment".

> While I am ok with having separate headings/pages for Java, Python, and Go functions, we can also have them together but just have different examples for different languages like:
> 
> https://spark.apache.org/docs/latest/quick-start.html
@jerrypeng It's great suggestion to adopt this structure. Smart idea. 
Do you know how to implement the switch pattern on our website? I mean switch between "Java/Python/Go examples".

**Comment by sijie** [comment]
IMO "Deployment" and "Function Deployment" will confuse users.

I actually have a slight different opinion after looking into the documentation of Azure Functions. I think we should differentiate the audience when categorizing the documentations

Here is the layout I suggest. 

- [ ] Overview : Basically describe the concepts for Pulsar Functions. This is for all audiences.
- [ ] Setup: Setup or configure a Pulsar cluster to run Pulsar Functions. It includes how to run Function workers and configure the runtime. This is for administrators.
   - [ ] Enable Pulsar Functions
   - [ ] Configure Runtime
- [ ] How-to: The how-to guide for developers
   - [ ] Develop: How to develop a pulsar function. (introduction of API)
   - [ ] Debug: How to unit test or debugging a pulsar function during development
   - [ ] Deploy: How to run/deploy a pulsar function.
   - [ ] Configure: How to configure to run a pulsar function
   - [ ] Monitor: How to monitor pulsar functions
   - [ ] Secure: How to secure or access secrets in pulsar functions (it is missing documentation at this moment)
   - [ ] Troubleshoot: How to trouble shoot running pulsar functions.

Since we only have one depth for the left navigation bar (due to the limitation of current documentation framework we use), the real name of the nav items can be different from the one I proposed. Mine is just an example.

The `how-to` guide can be organized using the tabs for different languages as what @jerrypeng proposed. Or we can just organize per-language how-to guide as what @Jennifer88huang proposed. Either works for me. 

Though the per-language how-to guide might be easier to implement given the current documentation framework and the frontend skills the community has.

<img width="377" alt="Screen Shot 2019-06-19 at 2 38 07 PM" src="https://user-images.githubusercontent.com/1217863/59803342-09e5f980-92a0-11e9-8b4f-b2105b1d9902.png">

https://docs.microsoft.com/en-in/azure/azure-functions/

**Comment by jerrypeng** [comment]
+1 on the structure @sijie proposed

**Comment by Jennifer88huang** [comment]
Great, we can adopt the new structure. 
Only one question, what's the differences between "Configure runtime" in the Admin part and "configure" in the developer part?

**Comment by sijie** [comment]
@Jennifer88huang 

It is the administrator's job to configure the runtime. the configuration is applied to the whole cluster.

"configure" a function means specifying the input, output, resources and etc when submitting a function. it is a per-function configuration.

**Comment by Jennifer88huang** [comment]
@sijie Thank you for clarifying it, so the "configure Functions runtime" parts we already have had in our website belongs to Admin part. And the "configure" section for developer part is much like user configuration info.

**Comment by sijie** [comment]
@Jennifer88huang well it is also a bit different from the "Admin" part. "Configure Functions runtime" is more related to the "Deployment" section.

**Comment by Jennifer88huang** [comment]
Sounds a little tricky, I'll check the information and re-adjust it. 
@wolfstudy  Any thoughts on Sijie's proposal?

**Comment by Jennifer88huang** [comment]
@sijie It seems that "Monitor / Secure / Troubleshoot" parts in How-to guides (dev part) are missing. Could anyone provide those content?

**Comment by sijie** [comment]
@jerrypeng has done a lot work in function metrics. @jerrypeng do you mind helping @Jennifer88huang at providing the content for that part?

**Comment by Jennifer88huang** [comment]
@jerrypeng Thank you very much if you could provide related raw materials.
You can also create PR with `functions-monitor`, `functions-secure`, `functions-troubleshoot` with the content. If there is anything I can do for you, feel free to contact me.
