### ISSUE TITLE
Publish Pulsar Helm chart on the official Helm Charts repository

### ISSUE THREAD

**Issue by banzo** [apache/pulsar#4687]
The Helm package manager provides an [official Charts repository](https://github.com/helm/charts) to publish charts to.

It would be nice if the [Pulsar Helm chart](https://github.com/apache/pulsar/tree/master/deployment/kubernetes/helm) was published on that repository.

Note: There has been some aborted attempts to do that in the past:

* https://github.com/helm/charts/pull/8756
* https://github.com/helm/charts/pull/1580

**Comment by youurayy** [comment]
Issues with the current Helm chart:

- some insane default values, e.g. 4 GB RAM for the Proxy component (and there are 3 replicas)
- a Helm redeploy which happens to restart the Broker (and possibly other) pods will render the cluster unusable
- there is no `RollingUpdate` defined on any of the deployments, so a Helm redeploy which affects these will restart all the pods at once (means no High Availability). (The `PodDisruptionBudget`s apply only on evictions [AFAIK](https://stackoverflow.com/questions/58064904/kubernetes-specifying-maxunavailable-in-both-deployment-and-pdb).)
- a Helm uninstall followed by a Helm (re)install with persistent volume claims will reattach the volumes, but Pulsar won't be able to use them and won't initialize properly, rendering it unusable
- changing a `ConfigMap` value and redeploying does nothing, pulsar components will keep using the old values
- the values.yaml config for Brokers doesn't allow exposing the broker service on NodePorts for direct (high performance) access thru the `pulsar://` protocol
- the Brokers should probably be deployed using a `StatefulSet` (just like BookKeepers are), as the RAM allocation is usually prohibitive of running multiple Brokers on the same node
- we should explain what Proxy really does (as Pulsar doesn't)
  - the `http://` protocol will only redirect your client to a direct/pod/ClusterIP `pulsar://` address, which will never work (unless you use EKS thru a VPC bridge -or- you have hardcoded your Broker URLs into the Proxy)
  - only the 'pulsar://` endpoint provides reverse proxying to the Brokers (but it needs a TCP load balancer, so e.g. you can't use Traefik 1.x to load balance multiple Proxies)
  - if your Brokers don't use SSL encryption, so can't your Proxy, because the the protocol type is carried thru Proxy, so you'll end up having to use unencrypted access thru public internet
  - due to these:
    - you'll really want to use only a small, single Proxy in your cluster for some external testing
    - for production use you'll want to expose the Pulsar Brokers on `NodePort`s, but since the Brokers do redirection for requests on topics they don't serve, you need to either:
      - set the `advertisedAddress` variable on the Broker to externally lookup-able hostname (in the context of your pulsar client) (the current Helm chart doesn't offer to do this, because you need to set a different one for each Broker)
      - somehow make the `hostname` on the Broker pod return externally lookup-able hostname (in the context of your pulsar client)

**Comment by youurayy** [comment]
Here's how (difficult it is) to currently achieve direct Pulsar Broker access on Kubernetes:

1. change Broker deployment to a `StatefulSet` (go by how the Bookkeeper deploy is spec'd)
2. change Broker service to type `NodePort` and add `externalTrafficPolicy: Local`
3. comment out the line `clusterIP: None` from the Broker service
4. change *both* Broker internal and external `pulsar://` ports to `30002` in `values.yaml`
    - this involves adding a `nodePort: 30002` line
5. add `brokerServicePort: "30002"` to Broker's configData in `values.yaml`
6. change `advertisedAddress` in Broker deploy from `status.podIP` to `status.hostIP`
7. use `pulsar://node1:30002,node2:30002/` type of URL for your Pulsar client

This way you can access your Kuberenetes Pulsar Brokers from the outside of the cluster and the topic redirections sent from Brokers to the Clients will work.

Just my 2 cents - if you care about wide adoption of Pulsar, you/we need to make this easier.

**Comment by vivekpd15** [comment]
@youurayy Any chances you have a working sample with you? It would be great if you can share.

**Comment by youurayy** [comment]
@vivekpd15 not yet, hopefully I can contribute at some later point. (private repo & too many other modifications)

Also on my local test env, the `externalTrafficPolicy: Local` (nor `service.beta.kubernetes.io/external-traffic`) wasn't honored (possible causes: CNI/Flannel, Hyper-V networking, or possibly https://github.com/kubernetes/kubernetes/issues/74383), so I had to use the proxy for external access.

**Comment by sijie** [comment]
The Helm Chart now is published to both Helm Hub and Artifact Hub.

Pulsar Helm Chart Repo: https://pulsar.apache.org/charts
Artifact Hub: https://artifacthub.io/packages/helm/apache/pulsar
Helm Hub: https://hub.helm.sh/charts/pulsar/pulsar
source code: https://github.com/apache/pulsar-helm-chart
