### ISSUE TITLE
Use timestamp as "__publish_time__" type in Pulsar SQL.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#4734]
### Motivation
"__publish_time__" is Pulsar SQL internal column, as Pulsar only stores timestamps, it doesn’t store the timezone information. Use timestamp  as "__publish_time__" type is more correct way in Pulsar SQL.

**Comment by codelipenghui** [comment]
@congbobo184 please take a look this issue.

**Comment by jerrypeng** [comment]
Please also make sure that the publish time predicate push down is still working correctly after this change:

https://github.com/apache/pulsar/blob/master/pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java#L323

**Comment by jerrypeng** [comment]
So I have done some experiments with changing __publish_time__ from TimestampWithTimeZoneType.TIMESTAMP_WITH_TIME_ZONE -> TimestampType .TIMESTAMP.  When I change the type, the predicate doesn't get pushed down correctly from Presto.  There seems to some issues with Presto.

Also this is another problem:

https://github.com/prestodb/presto/issues/6595

**Comment by codelipenghui** [comment]
@jerrypeng I try to change type of " __publish_time__" to  TimestampType .TIMESTAMP, and can pushed down correctly by using function ` from_iso8601_timestamp()`;

Here is my tests at superset:
![image](https://user-images.githubusercontent.com/12592133/61425472-a48e3280-a949-11e9-8499-abdc07312b4f.png)

Change value of " __publish_time__", the returned count of rows will be reduced accordingly:
![image](https://user-images.githubusercontent.com/12592133/61425593-fe8ef800-a949-11e9-8343-3a24dfafada9.png)

And i check the detail of returned rows, looks correctly:
![image](https://user-images.githubusercontent.com/12592133/61425638-23836b00-a94a-11e9-88a6-88aceb68499f.png)

**Comment by jerrypeng** [comment]
@codelipenghui predicate pushdown does not have anything to do with the correctness of the results.  Its an optimization we use in Pulsar SQL to retrieve only the data that satisfies the predicate from bookies since entries are sorted by publish time.  

Please take a look at this code:

https://github.com/apache/pulsar/blob/master/pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java#L295

In my tests, when I can TIMESTAMP_WITH_TIME_ZONE -> TIMESTAMP presto does not provide the correct predicate information for our connector to perform this optimization.

**Comment by codelipenghui** [comment]
@jerrypeng I have create a new PR and verified "__publish_time__" push down is work well, PTAL.
