### ISSUE TITLE
Support timezone information in Pulsar

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4823]
**Is your feature request related to a problem? Please describe.**

Currently all the time related types don't include timezone. Also Pulsar doesn't store any timezone information for both publish time and event time. This makes applications inconvenient on handling date types, specially when integrating Pulsar with popular BI tools.

This master issue is to discuss introducing timezone information for the date types in Pulsar.

1) Timezone in Schema.

Currently all time related types don't store any timezone information. We can do either:

a) introduce new schema type (e.g. timestamp_tz) to support storing timestamp along with timezone information. 
or
b) to store timezone information in the schema properties. so we can use schema properties to tell if the messages stores timezone information. we can then store the timezone information in the message headers.

2) Publish Time and Event Time.

Pulsar doesn't store and doesn't provide a method for applications to store timezone information. We can introduce two metadata fields `publish_time_tz` and `event_time_tz` to store the timezone information. 

---

Once Pulsar supports timezone information for `publish_time` and `event_time`, and support date schemas with timezone. We can improve Pulsar SQL to enable it using the timezone information.

**Comment by sijie** [comment]
@jerrypeng since this is related to what we discussed before, can you please take a look? The idea is to introduce timezone information in Pulsar.

/cc @codelipenghui

**Comment by jerrypeng** [comment]
I have a couple questions just to understand the rational behind having timezones with timestamp:

1.  Since all unix timestamp are in UTC time does it make sense to have timezone information for publish_time especially since it is set by the system?  In presto, for a timestamp field, by default it displays the time in the local timezone anyways

2. The user can set event_time, and from my understanding, users can offset the unix timestamp in UTC time by certain number of hours to correspond to a particular timezone.  Is this a best practice?  I am not an expert in how time should be represented in a database.  Just searching what other have said online:

https://justatheory.com/2012/04/postgres-use-timestamptz/

https://medium.com/@vivekmadurai/how-to-deal-with-date-and-time-across-time-zones-39b1bd747f35

Should we set or assume every timestamp to be in UTC time for consistency sake? Presto will display a timestamp field in local time

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant to the maintained versions.
