### ISSUE TITLE
'msgBacklog' is wrong when use Producer.sendAsync() send message

### ISSUE THREAD

**Issue by benxinglong** [apache/pulsar#4954]
**Describe the bug**
When use Producer.sendAsync() method send message to some topic( already has subscription),the value of 'msgBacklog' is wrong.

**To Reproduce**
1. use command "pulsar-client consume -s test -n 0 test" to create topic and subscription ,then exit
2. send 10 messages to Topic "test"  by  Producer.sendAsync()  
3. use command "pulsar-admin persistent stats test",check the value of 'msgBacklog'
4. the value of 'msgBacklog' is wrong

**Expected behavior**
The value of 'msgBacklog' should be 10

**Comment by sijie** [comment]
@benxinglong I am not sure if this is a problem. Because sendAsync are async operations. There is no guarantee that all 10 messages are sent to the topic. You have to wait on the futures returned by sendAsync to make sure all 10 messages are produced to the topic.

Please try to wait for the last sendAsync and check if you can get the right `msgBacklog`.
