### ISSUE TITLE
Pulsar-io connectors not all showing up in releases

### ISSUE THREAD

**Issue by thps** [apache/pulsar#5397]
Pulsar-io connectors that have been advertised as released are not all available for download.

**To Reproduce**
1. Go to http://apache.claz.org/pulsar/pulsar-2.4.1/connectors/ 
or https://pulsar.apache.org/en/download/
or list the 'pulsar-all' container 'connectors' directory.

2. Not all connectors in releases show up as NAR file artifacts as shown in
Release Notes or release branches.
See https://github.com/apache/pulsar/tree/branch-2.4/pulsar-io
and https://pulsar.apache.org/en/release-notes/ 

**Expected behavior**
Nar files should be released (be in the release list) and available for download. It should also likely be in the released pulsar-all docker image which comes with the connectors. Documentation should list them and their download links.

**Additional context**
I was looking for the Redis sink, it looks like others are missing also (flume, solr, etc).
The advertised release of Redis and those other sinks was in 2.4.0 per release notes.

**Comment by Anonymitaet** [comment]
@tuteng it seems that the connector download links on the http://apache.claz.org/pulsar/pulsar-2.4.1/connectors/ and https://pulsar.apache.org/en/download/ are incomplete?

If so, how can I add them?

**Comment by Anonymitaet** [comment]
@thps Thanks for your questions.

## #1
>1. Go to http://apache.claz.org/pulsar/pulsar-2.4.1/connectors/

If you want to download connector NAR files, see [here](https://archive.apache.org/dist/pulsar/), this is the **complete and most accurate list** for all Pulsar versions, from 2.1.0 to the latest (currently is 2.4.2).

>or https://pulsar.apache.org/en/download/

Thanks for reporting this issue.

Yes, the connector list in the `Pulsar IO connectors` section on the Pulsar download page are incomplete. 

Since the connector list is automatically generated from the `pulsar/site2/website/data/connectors.js` file, I've submitted a [PR](https://github.com/apache/pulsar/pull/5852) to fix this issue.

I will keep you updated once it is merged.

## #2
>Not all connectors in releases show up as NAR file artifacts as shown in
>Release Notes or release branches.
>See https://github.com/apache/pulsar/tree/branch-2.4/pulsar-io
>and https://pulsar.apache.org/en/release-notes/

NAR files are stored in other places rather than the following websites and they eat up much space.

- https://github.com/apache/pulsar/tree/branch-2.4/pulsar-io: **source code** of connectors are stored here.

- https://pulsar.apache.org/en/release-notes/: fixes, enhancements, PIPs and other highlights **about Pulsar release** are shown here.

@tuteng Please correct me if I'm wrong.
