### ISSUE TITLE
Geo replicator has ProducerBusyException

### ISSUE THREAD

**Issue by weishuisheng** [apache/pulsar#5698]
**Describe the bug**
We  replicate messages from Cluster A to Cluster B. The replicator failed when has exception.

[2019-11-19 18:00:13]10.1.2.79
content: 18:00:12.456 [pulsar-io-22-4] WARN org.apache.pulsar.broker.service.AbstractReplicator - [non-persistent://pxx/xx/ttt][pulsar-a -> pulsar-b] Failed to create remote producer (org.apache.pulsar.client.api.PulsarClientException$ProducerBusyException: Producer with name 'pulsar.repl.pulsar-a' is already connected to topic), retrying in 57.992 s

we use 2.4.1 .

**Comment by codelipenghui** [comment]
Since  https://github.com/apache/pulsar/pull/5571 handle the generated producer name, i think the producer name of replicator producer also can be considered as a producer with generated producer name, because only producer for a replicated topic.

So, we can handle it simple by considered replicator producer as generated name producer.
