### ISSUE TITLE
revert terminate topic 

### ISSUE THREAD

**Issue by laxpio** [apache/pulsar#5704]
**Is your feature request related to a problem? Please describe.**
sometimes need restrict publish message，when use terminate function，the topic will can not be reverted as a normal topic

**Describe the solution you'd like**
Support un-terminate function

**Comment by jiazhai** [comment]
@laxpio Thanks for open this issue. Do you mind share a little of your use case? why a topic is terminated but need to revert?

**Comment by laxpio** [comment]
case 1:
update/modify route function，before update function，need restrict message write to the topic，prevent dirty data from being written to other topics
case 2:
Misoperation

**Comment by Srar** [comment]
Same feature request.

**Comment by truong-hua** [comment]
Same expectation too

**Comment by codelipenghui** [comment]
Looks like we can just delete the terminated topic and create a new one with the same topic name? After the topic is terminated, the consumer can continue to consume messages. We can safely delete the topic after the backlogs have been cleaned up.

**Comment by truong-hua** [comment]
Thank @codelipenghui for a workaround solution but I think in reality, what will happen to us is that we have to force delete the topic and make sure that every consumer can re-subscribe properly to the new topic. Besides, creating a topic of our system is not as easy as just creating but it's a provisioning process with many configurations/policies has to be applied like retention, message rate, subscription policies and etc. So that why we expect a un-terminate/resume method which will help to prevent the re-provisioning of the topic with a lot of verifications later. To me, it's likely why we need the terminate feature while we can block publishers by restricting their IPs. Another point worth talking is that we don't expect to lose all topic history after the termination which is very important to our business requirements.

**Comment by codelipenghui** [comment]
> To me, it's likely why we need the terminate feature while we can block publishers by restricting their IPs. Another point worth talking is that we don't expect to lose all topic history after the termination which is very important to our business requirements.

I think it should not be a case that topic termination wants to resolve. We should only terminate the topic if we know the topic will not be used (producer first. consumes tries to drain the backlog then closes eventually.)

If the requirement is how to prevent the producers to publish new messages. I think we should use the publish rate limiter, backlog quota policy to block the producer or just a proxy to prevent producer connections.

**Comment by tisonkun** [comment]
Closed as answered.
