### ISSUE TITLE
Receive many emails for PR run failed CI-*

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#5898]
**Describe the bug**
After creating a PR, i received many emails notification on PR run failed CI-**. 

![图片](https://user-images.githubusercontent.com/29513837/71183032-2b0cbe80-22b2-11ea-8155-eeb09a6a51c6.png)

**Comment by jiazhai** [comment]
![image](https://user-images.githubusercontent.com/6348208/71251319-fefa4780-235c-11ea-8db9-df2763d5881c.png)
This is because you are watching this issue, and this issue experiencing a lot of ci error. try un-sub should resolve this issue. Would like to close this issue, feel free to open if not solved.

**Comment by huangdx0726** [comment]
@jiazhai  I'v tried as per your advice, i could't receive any notification, including whether the PR is approved or not.

**Comment by jiazhai** [comment]
@huangdx0726 . right, there is only 1 switch: receive all , or nothing.
