### ISSUE TITLE
[doc] 404 error in Pulsar Functions

### ISSUE THREAD

**Issue by huangdx0726** [apache/pulsar#6099]
**Describe the bug**
404 error in Pulsar Functions.

**To Reproduce**
1. Go to 'http://pulsar.apache.org/docs/en/2.4.2/functions-deploy'
2. Scroll down to end
2. Click on 'NEXT'

**Expected behavior**
Show correct page.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Jennifer88huang** [comment]
@huangdx0726 Thank you very much for reporting this issue. 
The reason for this issue is that we'll add more content on Pulsar configure, Monitor, secure and troubleshooting. The content is under construction. So you could not click "Next" at the end of the page. When the content is ready, the link to "Next" works automatically.
![image](https://user-images.githubusercontent.com/47805623/72716858-ec6a6c80-3bad-11ea-9c39-a03ae0efb3c1.png)

You can get full information on the new Pulsar Functions structure at https://github.com/apache/pulsar/issues/4554
