### ISSUE TITLE
Brokers constantly crash in the k8s cluster (Could not connect to bookie) after bookies ip change

### ISSUE THREAD

**Issue by Lanayx** [apache/pulsar#6154]
**Describe the bug**
Brokers constantly failing in a 2.5.0 GKE cluster with a _CrashLoopBackOff_ . They work for several hours and then fail. Tried installing clean cluster 3 days in a raw and the behavior persisted. Looks like there is a bookie discovering issue

**To Reproduce**
1. Use default helm chart values-mini.yaml on GKE 3 nodes
2. Use following values:
```
  # Pulsar proxy
  proxy: yes
  # Bookkeeper auto-recovery
  autoRecovery: no
  # Pulsar dashboard
  # Deprecated
  # Replace pulsar-dashboard with pulsar-manager
  dashboard: yes
  # pulsar manager
  pulsar_manager: no
  # Bastion pod for administrative commands
  bastion: yes
  # Monitoring stack (prometheus and grafana)
  monitoring: no
```
3. Wait for some time (4+ hours)

**Expected behavior**
Brokers should **not** fail with the CrashLoopBackOff error

**Screenshots**
![image](https://user-images.githubusercontent.com/3329606/73246774-80e15a00-41c0-11ea-9913-a24725282f8e.png)

**Additional context**
Adding logs from 2 failing brokers and 3 bookies. Also adding last logs from one of the evicted pods.
[bookeeper-1.log](https://github.com/apache/pulsar/files/4121328/bookeeper-1.log)
[bookeeper-2.log](https://github.com/apache/pulsar/files/4121329/bookeeper-2.log)
[bookeeper-3.log](https://github.com/apache/pulsar/files/4121331/bookeeper-3.log)
[broker-1.log](https://github.com/apache/pulsar/files/4121332/broker-1.log)
[broker-2.log](https://github.com/apache/pulsar/files/4121333/broker-2.log)
[evicted_broker.txt](https://github.com/apache/pulsar/files/4121424/evicted_broker.txt)

**Comment by jiazhai** [comment]
@Lanayx How is the status now? 
looks from `broker-1.log`, the first error is related to  net work routing error:
```
08:02:09.810 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.apache.pulsar.zookeeper.ZooKeeperDataCache - [State:CONNECTED Timeout:30000 sessionid:0x10003ed4ce001cf local:/10.52.1.88:58778 remoteserver:pu-pulsar-zookeeper-0.pu-pulsar-zookeeper/10.52.0.37:2181 lastZxid:4294976297 xid:142 sent:142 recv:143 queuedpkts:0 pendingresp:0 queuedevents:0] Received ZooKeeper watch event: WatchedEvent state:SyncConnected type:NodeDataChanged path:/loadbalance/brokers/10.52.1.88:8080
08:02:12.041 [bookkeeper-io-14-2] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0x53b792da]/10.52.2.61:3181, current state CONNECTING : 
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.52.2.61:3181
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_232]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_232]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [io.netty-netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
08:02:12.043 [bookkeeper-io-14-1] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0x47508154]/10.52.2.61:3181, current state CONNECTING : 
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.52.2.61:3181
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_232]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_232]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [io.netty-netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [io.netty-netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by Lanayx** [comment]
@jiazhai 
I've made one more experiment - left bare cluster without any load for several days and it looked healthy aftewards. Then I've connected bunch of consumers and producers (without sending any data) and it started failing. From what I saw, one of bookeeper pods was failing for short period of time during deploy (looks like due to pods rebalancing) and then it started working normally. However brokers couldn't handle such changes properly, attaching logs from two of them, one is stuck in CrashLoopBackOff, another marked as healthy on dashboard, but doesn't look healthy based on logs.
[failing broker.log](https://github.com/apache/pulsar/files/4158602/failing.broker.log)
[almost failing.log](https://github.com/apache/pulsar/files/4158603/almost.failing.log)

**Comment by Lanayx** [comment]
So I made a new try and the behavior persisted - the broker can't discover new bookies' adresses (once their ip address changes due to pod rebalancing). Looking at logs - broker can connect to _some_ bookies, but not to _all_ and therefore fails.
![image](https://user-images.githubusercontent.com/3329606/74015534-dcba9880-49a1-11ea-8a26-250eb12bb7f6.png)
For this picture I see the following logs:
Successfully connected to bookie: 10.52.2.46:3181
Could not connect to bookie: [id: 0x2ab0d298]/10.52.0.73:3181, current state CONNECTING
Could not connect to bookie: [id: 0x8dc696f7]/10.52.1.52:3181, current state CONNECTING

**Comment by sijie** [comment]
It seems that brokers can't form any ensembles because there are not enough bookies. 

We have enhanced the helm chart to include liveness and readiness probes for bookies and brokers. Can you try the latest helm chart for deploying Pulsar on Kubernetes? 

- follow the instructions (http://pulsar.apache.org/docs/en/kubernetes-helm/) to get started
- follow the instructions to configure (http://pulsar.apache.org/docs/en/helm-deploy/) the helm chart to install a production setup

**Comment by sijie** [comment]
@Lanayx Have checked my previous comment to see if that addressed your problem?

**Comment by Lanayx** [comment]
@sijie Thank you for the response, I'll check the fix next week, busy with other tasks at the moment

**Comment by tomgreenwood1** [comment]
I am having the same (or very similar) issue. The cluster runs fine for a bit and then brokers start failing and refusing connections. If I do a health-check on the broker I get

An unexpected error occurred in the server --- Message: org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available Stacktrace: java.util.concurrent.ExecutionException: org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) at org.apache.pulsar.broker.admin.impl.BrokersBase.healthcheck(BrokersBase.java:267) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104) at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) at org.glassfish.jersey.internal.Errors.process(Errors.java:316) at org.glassfish.jersey.internal.Errors.process(Errors.java:298) at org.glassfish.jersey.internal.Errors.process(Errors.java:268) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) at org.apache.pulsar.broker.web.ResponseHandlerFilter.doFilter(ResponseHandlerFilter.java:53) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:494) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) Caused by: org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available at org.apache.pulsar.broker.service.BrokerService$2.openLedgerFailed(BrokerService.java:895) at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$asyncOpen$8(ManagedLedgerFactoryImpl.java:343) at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:884) at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866) at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$2.initializeFailed(ManagedLedgerFactoryImpl.java:336) at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.lambda$null$1(ManagedLedgerImpl.java:402) at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) ... 4 more Caused by: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available

I deployed last friday, and then again yesterday, using the latest helm chart

**Comment by sijie** [comment]
@tomgreenwood1 

> Not enough non-faulty bookies available

It usually means that there are not enough bookies available. Can you confirm the followings:

- Can you use `kubectl` to check if you have enough bookies available? How many bookies are you running and what is the ensemble size configured?

**Comment by Lanayx** [comment]
@tomgreenwood1 I suspect that your case is different, `Not enough non-faulty bookies available` tells that bookies are not healthy rather than connection fails

**Comment by tomgreenwood1** [comment]
kubectl seemed to think that all the bookies were healthy, that's the strange thing. kuberenetes dashboard was all green for pulsar. I went with the official helm chart default, which I think is 3? It seemed to be triggered by me scaling up some other pods I had on the cluster.. but that could be a coincidence. I'm re-deploying again now, so I can gather more bookie logs if that would help? It's happened twice so far, and both times seems to be trigger by me scaling up/out my application pods..  One other thing I realised I that I hadn't been closing client connections properly in client code, and I was getting a lot of error messages from the clients about stale connections, already deleted connections..

**Comment by tomgreenwood1** [comment]
Just an update from me, after a re-deploy and things seem to be working fine now. The things I changed were:

1. I double-checked I had the latest helm chart by pulling the pulsar repo again (git reported a couple of updates on master).
2. I placed all my nodes in the same availability zone (I am on AWS EKS).
3. I Added to client.close() on a SIGTERM to all my client code, in case it was unclosed connections causing an error.
4. I replaced the nodes in my EKS cluster with bigger nodes.

So I'm not sure what made the difference, but its working ok now. I've been hitting it with ~10k messages/second for a few hours and no problems. So I'll scale up and see how it goes.

Thanks for the help

**Comment by sijie** [comment]
@tomgreenwood1 great news! Good to know you have figured the problem out.

**Comment by tomgreenwood1** [comment]
One more update from me. Apologies if this is a different issue (maybe related?). My issue is happening again, and  the bookie logs are showing:

```bash
10:59:39.505 [LedgerDirsMonitorThread] WARN  org.apache.bookkeeper.bookie.LedgerDirsMonitor - LedgerDirsMonitor check process: All ledger directories are non writable
10:59:39.506 [LedgerDirsMonitorThread] ERROR org.apache.bookkeeper.util.DiskChecker - Space left on device /pulsar/data/bookkeeper/ledgers/current : 2621739008, Used space fraction: 0.95026135 > threshold 0.95.
```

looks like I need to change a retention setting or something like that?

**Comment by sijie** [comment]
@tomgreenwood1 It means the disk usage is over 95% so the bookie is forced to run in readonly mode. You can increase `diskUsageThreshold` in the bookie's configuration to `0.99`. This would help bookies get out of readonly mode.

**Comment by Lanayx** [comment]
I was still getting this issue with 2.5.2, however 2.6.0 cluster seems to be stable, so closing the issue.
