### ISSUE TITLE
Windowed consumers/functions

### ISSUE THREAD

**Issue by avillev** [apache/pulsar#6166]
Using Kafka Streams, I was able to use WindowedStreams to filter and rate limit the events of a topic over time based on event priorities.
Ex: Only 5 messages are accepted per second. We only take the most important ones within one second.
I have been checking Pulsar functions to achieve the same thing and could not find a way.

I would love to have the possibility in a pulsar function or in a consumer, to consume/process windowed batches of elements to be able to do the same thing.

**Comment by codelipenghui** [comment]
Batch receiving for consumer was supported in 2.5.0, here is the documentation for batch receiving : http://pulsar.apache.org/docs/en/client-libraries-java/#batch-receive

Pulsar supports window function since 2.1.0, looks there is no document for window function. I think you can see the example of window function 

https://github.com/apache/pulsar/blob/master/pulsar-functions/java-examples/src/main/resources/example-window-function-config.yaml  

https://github.com/apache/pulsar/blob/master/pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/AddWindowFunction.java

**Comment by avillev** [comment]
Wonderful, with this and that I should be able to do the same thing :). Thank you

**Comment by avillev** [comment]
I have checked the examples but it does not seem to be the same thing. 

To have the equivalent of the TimedWindow feature of Kafka stream we would need a function that takes only the messages from t1 to t2 periodically. 
Neither the batch consumer and those window functions would allow us the do the same.

Is there a way to do that?

**Comment by codelipenghui** [comment]
You can try to set `windowLengthDurationMs` to start a time based window function. Because there is no example or documentation for time window function.

**Comment by avillev** [comment]
Hum, okay. Shouldn't we consider adding an example in the documentation?

**Comment by codelipenghui** [comment]
Yes, here is a issue track the function documentation https://github.com/apache/pulsar/issues/5520 , if you are interested in contribution, welcome!

**Comment by jiazhai** [comment]
@avillev @codelipenghui Is it ok to close this issue?

**Comment by codelipenghui** [comment]
Yes, #5520 is tracking the documentation of windowed function

**Comment by avillev** [comment]
I guess it is yeas :)
