### ISSUE TITLE
Client flow permits calibration

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6255]
**Is your feature request related to a problem? Please describe.**
We have met a lot of problems related to consumption stuck. Most of the reasons related to permits sync from broker and client. So it's necessary to introduce a mechanism for clients and brokers permits calibration when consumption stuck.

This is a tracker to track this feature.

**Comment by devinbost** [comment]
Thanks for creating this issue. I'm actively working on it, but I haven't found a clear root cause yet.
What I've noticed, however, is that the client consumer has the correct number of permits, but the broker dispatcher and broker Consumer are getting negative permits.
What's strange is that some people do not seem to experience this issue in their clusters, so it seems that there may be a configuration that toggles the issue.

**Comment by devinbost** [comment]
It's also possible that only certain kinds of workloads trigger the issues.
We've seen this issue in function workloads using shared subscriptions with one or more consumers per topic (but only one consumer per subscription) on persistent topics. 
When looking at a heap dump, the dispatchers all used `PersistentDispatcherMultipleConsumers`. I'll post more information about the heap dump details on #6054
