### ISSUE TITLE
libssl.so should be linked dynamically into the libpulsar.a

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#6439]
libssl.so should be linked dynamically into the libpulsar.a or it would bring in security issue.

>I believe this is a long term operational security issue, the libssl.so should be linked dynamically into the libpulsar.so so that the system defined libssl.so or customer provided libssl.so may be used. This should allow independent patching of the ssl library without the need to redelivery a new libpulsar.so.
>
>It would be great to get a libpulsar.so that can be linked, that does not have the direct compile dependency.

**Comment by aahmed-se** [comment]
we can use static or dynamic linking in cmake, what's the issue ?

**Comment by sijie** [comment]
@aahmed-se 

In this use case, the customer is building a database plugin which is a dynamic linking library that will be shipped to all database machines. The customer will statically link `libpulsar.a` so they just need to ship libpulsar.a along with their library. They don't need to install `libpulsar.so` and its dependencies. 

However we shouldn't static link `libssl` in libpulsar.a, as this is a security red flag. we should just use whatever the libssl the system provides. Because if there is a security problem in libssl, all the machines can just update their own libssl library without rebuilding libpulsar.a.
