### ISSUE TITLE
Python client `consumer.receive()` call suspends processing of interrupts within the program

### ISSUE THREAD

**Issue by bry00** [apache/pulsar#6477]
**Describe the bug**
Python client `consumer.receive()` call suspends processing of interrupts within the program 
(including SIGTERM, SIGINT) which makes difficult to implement graceful shutdown.

There was a [similar issue](https://github.com/apache/pulsar/pull/675) some time ago, but it was obviously not implemented.

**To Reproduce**
1. Run the following Python code for the empty topic:
```Python
import signal
import pulsar

def shutdown_signal_received(signum, frame):
    print("Received system signal {} ({}).".format(signum, signame), flush=True)

signal.signal(signal.SIGINT, shutdown_signal_received)
signal.signal(signal.SIGTERM, shutdown_signal_received)

client = pulsar.Client('pulsar://localhost:6650')
consumer = client.subscribe('abcd', subscription_name='xyz',  consumer_type=pulsar.ConsumerType.Shared)

msg = consumer.receive()
```
2. See error: receive hangs and suspends interrupts if the input queue is empty. 
    For example results of the `kill -15` command would be seen only if new data message is sent is 
    provided though the topic.

**Expected behavior**
`receive()` call should be interrupted (at least) on registered exception, and empty (`None`) result should
 be returned and / or appropriate Pulsar exception should be raised.

**Desktop (please complete the following information):**
 - OS: macOS Catalina, 10.15.3

**Comment by bry00** [comment]
Any info on the solving status of this issue?

**Comment by danielorf** [comment]
@bry00 Any new developments here?  I'm having the same problem on v2.7.1.

**Comment by bry00** [comment]
> @bry00 Any new developments here? I'm having the same problem on v2.7.1.

Sorry, I have no idea.

**Comment by gw9i** [comment]
@jiazhai @sijie Any developments? Is there any chance for fix of the issue in the next release?

**Comment by drunksaint** [comment]
i'm facing the same problem in 2.9.1

**Comment by zbentley** [comment]
This remains a problem with the current client. For SIGINT to be received by a Python program, you have to do one of two thigns:
- call `receive` with a timeout, in which case the signal will be received after the timeout.
- use a `message_listener` handler, which really changes guarantees and behavior.

Other network service drivers are interruptible when in their `receive` operation; can this one be? At least on Linux, it looks like Boost is calling `read` when there's no data in the socket, rather than using an interruptible multiplexer (e.g. poll/epoll/select) to wait until data is ready; the latter would allow operations to respond to signals. Nonblocking reads with a socket-timeout set are also an option.
