### ISSUE TITLE
Broker and Proxy support multiple CA certs

### ISSUE THREAD

**Issue by bmyers-csu** [apache/pulsar#6640]
I'm requesting the Broker and Proxy be updated to support multiple CA certs. I have a requirement that internal communication uses an internal CA cert and we allow customers to define their own CA cert alongside.

**Comment by wmccarley** [comment]
If you're talking about your brokers accepting multiple CAs in tlsTrustCertsFilePath I _think_ that is already supported. You should be able to cat all the ca pem files into one big file and use that as your trust cert store. I have not done it personally because we have no such requirement but I think it will work. You will get a pem file like this:
`-----BEGIN CERTIFICATE-----`
`<your CA>`
`-----END CERTIFICATE-----`
`-----BEGIN CERTIFICATE-----`
`<their CA>`
`-----END CERTIFICATE-----`
