### ISSUE TITLE
Failing to acknowledge messages during pulsar reconnection 

### ISSUE THREAD

**Issue by pradeep00m** [apache/pulsar#6731]
**Describe the bug**
I am consuming messages from the topic and acknowledging them. For some reason pulsar lost the connection and reconnects back and acknowldge the message. Its not getting acknowledged.

**To Reproduce**
1. Create a consumer and consume a message from the topic.
2. store the message and close the connection
3. Create the consumer and acknowledge the message now.
4. If I consume from the consumer now, I'm getting the same previous message.
Because of this I'm getting duplicate messages. 

**Expected behavior**
I should be able to acknowledge the message and recive the next message. Not the same message again.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04.1 LTS]

**Comment by codelipenghui** [comment]
Looks the problem is the message does not remove from the receiver queue when the consumer acknowledges messages. So it's better to skip messages that already acknowledged by the consumer.

BTW, currently, message acknowledgment is asynchronous execution. Even if you ack a message then the consumer reconnects occurs, the consumer will also receive duplicate messages.

**Comment by pradeep00m** [comment]
> So it's better to skip messages that already acknowledged by the consumer.

How will I know if the message is already acknowledged? Right now I'm consuming from the consumer and do the necessary processing.

**Comment by codelipenghui** [comment]
> How will I know if the message is already acknowledged? Right now I'm consuming from the consumer and do the necessary processing.

**Comment by tisonkun** [comment]
Closed as stale and no one works on it. Please create a new issue if it's still relevant to the maintained versions.
