### ISSUE TITLE
k8s deploy values.yaml metadataPrefix: "/configuration-store"

### ISSUE THREAD

**Issue by lookhua** [apache/pulsar#6819]
in k8s helm deploy mode.
when i set metadataPrefix: "/configuration-store"
and set 
components:
   zookeeper: true
   bookkeeper: true
   broker: true
other components is false in the values.yaml  
then run command:  helm install -n test-pulsar-cluster -f values.yaml ./
all the Stateful Sets pending except zookeeper 

when i set the  metadataPrefix: "/configuration-store" to "", it works.

**Comment by sijie** [comment]
Can you describe more about the sequence to reproduce this behavior?

**Comment by moliqingwa** [comment]
Same issue.
If let metadataPrefix be empty, then all pods runs soothly.
If metadataPrefix was configured, then some pods would run error. Here are the issues of pulsar-pulsar-init-xxxx:
===============================================
│ ulsar-bookkeeper-verify-clusterid 15:11:21.203 [main] ERROR org.apache.bookkeeper.discover.ZKRegistrationManager - BookKeeper metadata doesn't exist in zookeeper. Has the   │ ulsar-bookkeeper-verify-clusterid 15:11:21.316 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x3003591b05a017d
│ ulsar-bookkeeper-verify-clusterid 15:11:21.316 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x3003591b05a017d closed                                               │ ulsar-bookkeeper-verify-clusterid Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: org.apache.bookkeeper.bookie.BookieException$Me
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:61)                                 │ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.bookie.BookieShell$WhatIsInstanceId.runCmd(BookieShell.java:1453)
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:236)                                                     │ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2235)
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2326)                                                                │ ulsar-bookkeeper-verify-clusterid Caused by: java.util.concurrent.ExecutionException: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: Failed to get cl
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:352)                            │ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:372)
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:49)                                 │ ulsar-bookkeeper-verify-clusterid     ... 4 more
│ ulsar-bookkeeper-verify-clusterid Caused by: org.apache.bookkeeper.bookie.BookieException$MetadataStoreException: Failed to get cluster instance id                          │ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.discover.ZKRegistrationManager.getClusterInstanceId(ZKRegistrationManager.java:429)
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.lambda$apply$0(InstanceIdCommand.java:52)                        │ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.meta.MetadataDrivers.lambda$runFunctionWithRegistrationManager$1(MetadataDrivers.java:372)
│ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:347)                            │ ulsar-bookkeeper-verify-clusterid     ... 6 more
│ ulsar-bookkeeper-verify-clusterid Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for BookKeeper metadata                          │ ulsar-bookkeeper-verify-clusterid     at org.apache.bookkeeper.discover.ZKRegistrationManager.getClusterInstanceId(ZKRegistrationManager.java:419)
│ ulsar-bookkeeper-verify-clusterid     ... 9 more                                                                                                                             │ ulsar-bookkeeper-verify-clusterid JMX enabled by default
│ ulsar-bookkeeper-verify-clusterid 15:11:30.352 [main] INFO  org.apache.bookkeeper.meta.MetadataDrivers - BookKeeper metadata driver manager initialized

**Comment by tisonkun** [comment]
Closed as stale. The development of pulsar-helm-chart is moved to https://github.com/apache/pulsar-helm-chart.

If it's still relevant, please open an issue there.
