### ISSUE TITLE
Pulsar add bookie failed, and not retry

### ISSUE THREAD

**Issue by Shoothzj** [apache/pulsar#7451]
Our reliability test, when restarting zookeeper, the node of the bookkeeper first registered with zk, and then passed the health check of k8s (that is, the bk domain name can be accessed at this time). Then when pulsar adds the bk node
, Because the domain name could not be parsed, and then did not try again (because ZKRackMapping where the configured useHostName is false). useHostNameAsBookieID is wrong ? We use statefulset deploy mode of bk, and wish restart does not corrupt bk's data.

**Comment by sijie** [comment]
@Shoothzj 

The NPE when resolving network address is fixed in bookkeeper and released as part of upcoming 4.11 release. We will bump Pulsar's dependencies soon.

The `useHostName` in ZKRackMapping has been fixed in the latest master and will be released in upcoming Pulsar releases (2.7.0 and 2.6.1)
