### ISSUE TITLE
Set jvm options to each components

### ISSUE THREAD

**Issue by wenjun8888** [apache/pulsar#7574]
sir, i have an questions to ask.
when i setting jvm options in pulsar_env.sh
for example:
```
# Extra options to be passed to the jvm
PULSAR_MEM=${PULSAR_MEM:-"-Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g"}
```
Is that means  4g memory allocated for each components.
In my case, a node with 8G memory and there are zookeeper\bookie\broker on it.
So i think 8G is not enough...
Please tell me if i have the wrong idea, or can i set jvm options for singel components.
Thank you very much!

**Comment by wolfstudy** [comment]
You should configure `PULSAR_MEM` to allocate memory for running Pulsar components.

 - It is recommended to configure `-Xms` to equal to `-Xmx`, so that JVM can allocate the whole heap memory during initialization.
- Since Pulsar uses direct memory extensively, you should make sure allocating enough directory memory for JVM. It is recommended to configure `-XX:MaxDirectMemorySize` to be twice of `-Xmx`.
- Make sure the total size of JVM heap and direct memory does *NOT* exceed the total available memory on your machine. It is also recommended to leave at least 1~2 GB for your operating system.

Let’s use a 8GB machine as an example, you can configure your maximum heap memory to be 2GB, directory memory to be 4GB and leave the remaining 2GB for your operating system. So your `PULSAR_MEM` will be:

```
-Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g 
```

**Comment by sijie** [comment]
@wenjun8888 Can you check @wolfstudy 's question?

**Comment by wolfstudy** [comment]
ping @wenjun8888 , will close this issue, If you have any questions about this, please reopen it or let me know, thanks.
