### ISSUE TITLE
Missing KEY_BASED option from BatchBuilder for C++ Client

### ISSUE THREAD

**Issue by wongkimshing** [apache/pulsar#7800]
**Is your enhancement request related to a problem? Please describe.**
When we wanna receive messages with **KEY_SHARED** mode with Java consumer, we found there is no **KEY_BASED** option from **BatchBuilder** for C++ producer. It's kind of frustrated for the integration between C++ & Java programs.

**Describe the solution you'd like**
Add **KEY_SHARED** mode for C++ client and **KEY_BASED** option from **BatchBuilder** as well.

**Comment by BewareMyPower** [comment]
1. You can set consumer type of `ConsumerConfiguration` to use key shared subscription.
2. C++ client doesn't support key based batching yet.  I did some work about key based batching last month, but I'm a little busy recently so I didn't continue. It's not a difficult feature but it needs much code refactoring for C++ client.

**Comment by wongkimshing** [comment]
@BewareMyPower 

1. You mean Java consumer with KEY_SHARED mode and C++ producer without KEY_SHARED mode are working well for KEY_SHARED?
2. Could you please take some time on it? Really appreciate.

**Comment by BewareMyPower** [comment]
@wongkimshing 

First make it clear that KEY_SHARED is a subscription mode for consumers, key based batching is a feature of batching for producers. You can send messages **without batching** by C++ client, and consume these messages using KEY_SHARED subscription by Java client.

1. I mean C++ **consumer** can subscribe topics with KEY_SHARED mode.
2. Yeah, I'd like to continue the [development](https://github.com/BewareMyPower/pulsar/commits/key-based-batch-dev). I may just have more time after this week.

**Comment by BewareMyPower** [comment]
I've just pushed a PR #7996 to support key based batching. There're a lot of changes so it may take some time to review.

You can see [KeySharedConsumerTest.cc](https://github.com/apache/pulsar/blob/bf55c95b5ff65e7ed2eb78617f2e183b77d47aa4/pulsar-client-cpp/tests/KeySharedConsumerTest.cc) as an example. Just change the batching type of producer:

```c++
            ProducerConfiguration()                                                //
                .setBatchingType(ProducerConfiguration::KeyBasedBatching)          //
                /* set other configs... */
```

**Comment by BewareMyPower** [comment]
Close this issue since it is supported now.

**Comment by joshua-motorq** [comment]
@BewareMyPower 
After your #7996
Can you confirm if multiple batches (with different keys) would be optimised and sent out with a single network request?

**Comment by BewareMyPower** [comment]
Yes. It's also added to Python client in https://github.com/apache/pulsar/pull/8185 but not available in the Node.js client yet.

**Comment by joshua-motorq** [comment]
@BewareMyPower Got it

Just to confirm because i feel like i didnt properly phrase it in my earlier question, really sorry!

With key_based batcher enabled, and i queue 100 messages, with keys k1, k2 and k3

And then i flush from the producer

Would all this be optimisd to only be one network call?

Again, apologies for the ambiguous question earlier!

**Comment by joshua-motorq** [comment]
Feel like this would be beneficial to be mentioned in the docs as well, if you'd agree, i'll submit a PR for that!

**Comment by joshua-motorq** [comment]
This was where the question came from, Tried looking under the hood

From the source code, it's clear that `BatchMessageKeyBasedContainer` stores messages in batches based on their key (either ordering key or partition key). The `add` method adds messages to the appropriate batch, and `createOpSendMsgs` creates `OpSendMsg` objects for each batch.

The `createOpSendMsgs` function iterates through the `batches_` map and creates a separate `OpSendMsg` for each non-empty batch. The `OpSendMsg` objects are then sorted by sequence ID and returned in a vector. This indicates that multiple `OpSendMsg` objects, each containing messages with the same key, are created. Or atleast this is what i understand

`sendMessage` is called for each `OpSendMsg` object. Since `BatchMessageKeyBasedContainer::createOpSendMsgs` creates a separate `OpSendMsg` for each key. It then serializes the message using `Commands::newSend` and then calls `asyncWrite`, which inturn directly calls `ASIO::async_write` on the socket.

this was where the question came from, i was not exactly able to pin point the place where we are able to send multiple batches each of different keys in the same network request @BewareMyPower
