### ISSUE TITLE
Pulsar client output the auth info may reveal sensitive information

### ISSUE THREAD

**Issue by tabalt** [apache/pulsar#8109]
**Is your enhancement request related to a problem? Please describe.**

Pulsar client output the auth info may reveal sensitive information

**Describe the solution you'd like**

Remove auth information from log

**Additional context**
INFO o.a.p.c.i.ProducerStatsRecorderImpl:102 - Pulsar client config: {
  "serviceUrl" : "pulsar://127.0.0.1:6650",
  "authPluginClassName" : "org.apache.pulsar.client.impl.auth.AuthenticationToken",
  "authParams" : "sensitive_authParams",
  "authParamMap" : sensitive_authParamMap,

**Comment by racorn** [comment]
Unfortunately, this breaks configuration of authentication parameters with a property map supported by

`PulsarClient.builder().loadConf(configMap)`

like TLS client certificate authentication (where this is no sensitive information, just filenames).

It breaks because the way `ConfigurationDataUtils.loadData` is implemented, where the configuration data is serialized to a string before it is deserialized back to a desired type (and loose the fields annotated with JsonIgnore).
