### ISSUE TITLE
Effectively-Once support for WebSockets

### ISSUE THREAD

**Issue by cvuijst** [apache/pulsar#8175]
**Is your feature request related to a problem? Please describe.**
On the Pulsar client feature matrix, the "**Effectively-Once**" feature is not available for the WebSocket client. The matrix seems currently updated till Pulsar 2.5.0, see [here](https://github.com/apache/pulsar/wiki/Client-Features-Matrix). Is there any chance this will be supported in the future? Or does anyone have experience how to make this happen in a different way?

**Describe the solution you'd like**
Solution preferred to be embedded through the Pulsar WebSocket server.

**Describe alternatives you've considered**
Alternatives might be:

- Enhance the messages send and acknowledges received to impose effectively once tracking at the client side.
- Enhance documentation how this can be achieved in another way outside the Pulsar scope. For example, an end to end scenario that proves effectively once based on WebSocket integration.

**Additional context**
This issue is created as follow up on the Pulsar Slack Channel # general, message: https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1601446017085700

**Comment by BewareMyPower** [comment]
The WebSocket already supports effectively-once because the client side only needs to set producer name and timeout, i.e. `sendTimeoutMillis` and `producerName`. See http://pulsar.apache.org/docs/en/client-libraries-websocket/#producer-endpoint for details.

The effectively-once means message deduplication from producer side, see http://pulsar.apache.org/docs/en/cookbooks-deduplication/#pulsar-clients

And the equivalent Python code through WebSocket is:

```python
import websocket

url = 'ws://localhost:8080/ws/v2/producer/persistent/public/default/topic-1?producerName=producer-1&sendTimeoutMillis=0'
ws = websocket.create_connection(url)
```

It should be supported a long time ago but the client feature matrix in wiki was wrong.

**Comment by cvuijst** [comment]
Sounds like a solution, thank you for the additional description.
