### ISSUE TITLE
The REST API  to create source is not correct

### ISSUE THREAD

**Issue by ZhuJiang121** [apache/pulsar#8262]
I found params it need is "sourceConfig" and "url" ,but the REST API documents is not true,

[https://pulsar.apache.org/source-rest-api/?version=2.6.1&apiversion=v3#operation/registerSource](https://pulsar.apache.org/source-rest-api/?version=2.6.1&apiversion=v3#operation/registerSource)

**Comment by Jennifer88huang** [comment]
@tuteng @zymap could you please help check it? Thank you.

**Comment by BewareMyPower** [comment]
You're right, I've opened the similar issue before, see #7625 . The REST API to create or update a source/sink is `multipart/form-data`.

`url` is not the only undocumented params, see  https://github.com/apache/pulsar/blob/9c821cf940d422d2ea3d47687bd309fe698ab84e/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java#L79-L81

I've seen many people being confused with these REST APIs, but it's hard to document `uploadedInputStream` and `fileDetail`. Also I'm not sure how to use other languages to construct the HTTP body, because `uploadedInputStream` and `fileDetail` are Java classes.

Therefore, the only way I can think of is just using the `pulsar-admin` to create/update source/sink.

**Comment by tisonkun** [comment]
We're using the redoc lib to generate swagger page. It seems not be able to support multipart parameter documents: https://github.com/swagger-api/swagger-core/issues/3070 and https://github.com/Redocly/redoc/issues/707.

Closed as stale. It's far more complex to switch to a better framework or overcome the upstream shortcoming.
