### ISSUE TITLE
[Schemas] only auto update if schema is different than current

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#8682]
**Is your enhancement request related to a problem? Please describe.**
Currently when a producer contains a schema it is takes as topic Schema and schema version is incremented even if the schema has not changed between producer restarts.

**Describe the solution you'd like**
On allow auto update schema, only update it if the schema changed.

**Comment by codelipenghui** [comment]
@KannarFr This expected behavior is the schema will update once the schema is changed. If a producer with the same schema but the schema version is incremented after the producer restart, I think this is a bug. Could you please provide more information about this issue? Which Pulsar version are you using (broker and client) and It would be best if there is a reproducible example

**Comment by KannarFr** [comment]
@codelipenghui 2.6.2 broker and pulsar-rs latest client. Will try to create a reproductible case.
