### ISSUE TITLE
[Pulsar Client Cpp] memory leak when receive async

### ISSUE THREAD

**Issue by ltamber** [apache/pulsar#8846]
**Describe the bug**
Currently when the consumer invoke `receiveAsync()`, there will a callback push to `pendingReceives_ `, https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/lib/ConsumerImpl.cc#L644, but if where has no more message in the topic, the callback in  `pendingReceives_` will not pop anymore, and lead to memory leak.

**To Reproduce**
1. invoke `consumer.receiveAsync()` in a for loop, and don't produce any message to the same topic

**Comment by BewareMyPower** [comment]
Firstly it's true, not like the producer's send operation, consumer's receive operation has no timeout. So calling `receiveAsync` infinitely without any limit while no messages could be received will make pending receives in memory growing infinitely.

However, you can add the limit for the number of pending receives from a client side:

```c++
#include <pulsar/Client.h>
#include <mutex>
#include <condition_variable>

using namespace pulsar;

struct PendingReceiveTracker {
    std::mutex mutex_;
    std::condition_variable cond_;

    size_t numPendingReceives_ = 0;
    const size_t maxNumPendingReceives_;

    PendingReceiveTracker(size_t maxNumPendingReceives) : maxNumPendingReceives_(maxNumPendingReceives) {}

    void beforeReceiveAsync() {
        std::unique_lock<std::mutex> lock(mutex_);
        while (numPendingReceives_ >= maxNumPendingReceives_) {
            // TODO: you can add other handler instead of wait here
            cond_.wait(lock);
        }
        numPendingReceives_++;
    }

    void completeReceiveAsync() {
        std::unique_lock<std::mutex> lock(mutex_);
        if (numPendingReceives_ == 0) {
            return;
        }
        numPendingReceives_--;
        cond_.notify_all();
    }
};

int main() {
    Client client("pulsar://localhost:6650");
    Consumer consumer;
    client.subscribe("my-topic", "consumer-1", consumer);  // ignore the returned value check here

    PendingReceiveTracker tracker(1000);
    for (int i = 0; i < 100000; i++) {
        // When the pending receives achieve 1000, this method blocks here until any message is received.
        // You can also change the strategy, see the TODO in beforeReceiveAsync()
        tracker.beforeReceiveAsync();
        consumer.receiveAsync([&tracker](Result result, const Message& msg) {
            if (result == ResultOk) {
                tracker.completeReceiveAsync();
                // TODO: process `msg`
            } else {
                // TODO: handle error
            }
        });
        // do other things here...
    }

    client.close();
}
```

As for a timeout limit, it's a little more complicated that a timer is needed.

Let's go back to the timeout case. Send timeout means some specific messages' associated responses are not received during the timeout. Users can choose to reproduce **the same messages** again if they don't care message duplication.

However, unlike the send timeout, receive timeout is not related to any message. So when you encounter the timeout with N pending receives, what will you do? Clear these pending receives? OK, then you'll add more pending receives again.  Clear and then re-add the pending receives is not much different with make these receives continue pending. The only behavior that make much difference is stop receiving, like triggering an alarm.

A simpler way is just calling `receive()` with a timeout. IMO, `receiveAsync()` doesn't has any more significant benefit than `receive(Message& msg, int timeout)` except waiting for multiple messages at the same time. C++ client doesn't provide something like Java's `CompletableFuture`, so you need to play tricks with the callback.

**Comment by BewareMyPower** [comment]
I think the issue is similar to #8300 . Bur unlike the Java Client, C++ API only exposes the receive callback so there's no case like a future of receive is cancelled but the associated pending receive is still in the queue.

The C++ client's receive logic is more simple:

1. Add a pending receive when `receiveAsync` is called.
2. Remove a pending receive when an incoming messages is received by `ClientConnection`, while the callback of `receiveAsync` is called.
3. Clear all pending receives and complete all associated callbacks when the consumer is closed.

If you want to cancel a pending receive, the only way is to close the consumer. So adding a receive count limit is needed.

By the way, if you don't want to introduce the conditional variable and notify/wait, a simple way is:

```c++
    std::atomic_int numPendingReceives{0};
    for (int i = 0; i < 100000; i++) {
        if (++numPendingReceives >= 1000) {
            // TODO: wait for a few milliseconds? or sending alarms?
        }
        consumer.receiveAsync([&numPendingReceives](Result result, const Message& msg) {
            numPendingReceives--;
            if (result == ResultOk) {
                // TODO: process `msg`
            } else {
                // TODO: handle error
            }
        });
        // do other things here...
    }
```

**Comment by ltamber** [comment]
@BewareMyPower thanks for your detail reply, I think client side should avoid these risk which will cause application unstable but not depend on some workaround on application size.

**Comment by BewareMyPower** [comment]
@ltamber The cost of flexibility is the complexity. It's not like `sendAsync` vs. `send`, `receive(Message&, int)` is easy and enough to use in most cases. The only case to use `receiveAsync` is to wait multiple messages.

If you're using Java client, when you choose `receiveAsync`, the logic will still be complicated.

Let's start with a simple client code:

```java
        try (PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build()) {
            Consumer<byte[]> consumer = client.newConsumer()
                    .topic("my-topic")
                    .subscriptionName("my-sub")
                    .subscribe();
            for (int i = 0; i < 100000/* just to represent a large number */; i++) {
                consumer.receiveAsync().whenComplete((msg, e) -> {
                    if (e == null) {
                        // TODO: process `msg`
                    } else {
                        // TODO: handle error
                    }
                });
            }
        } catch (PulsarClientException e) {
            e.printStackTrace();
        }
```

The issue is the same. If there're no messages, the pending receives queue will grow infinitely until OOM.

Then you need to manage these futures, e.g.

```java
            ArrayBlockingQueue<CompletableFuture<Message<byte[]>>> queue = new ArrayBlockingQueue<>(1000);
            for (int i = 0; i < 100000; i++) {
                CompletableFuture<Message<byte[]>> future = consumer.receiveAsync();
                queue.put(future); // it blocks when the queue is full
                future.whenComplete((msg, e) -> {
                    if (e == null) {
                        // TODO: process `msg`
                    } else {
                        // TODO: handle error
                    }
                    queue.poll(); // just to release a space
                });
            }
```

So it's like the first C++ example. The code looks more simple just because `ArrayBlockingQueue` has already encapsulated the conditional variable. Also,

As for the second C++ example, instead of using `queue.put(future)`:

```java
                if (!queue.offer(future)) {
                    // TODO: handle the queue is full error to make sure the next queue.add won't fail
                    queue.add(future);
                }
```

You can just wait for a while, or after #8326 , you can call `cancel` here to remove all pending receives:

```java
                if (!queue.offer(future)) {
                    queue.forEach(futureInQueue -> futureInQueue.cancel(true));
                    queue.add(future);
                }
```

The code looks more simple but it's just because Java standard library is more strong. You still have to handle the corner cases from a client side instead of relying on the library.

**Comment by tisonkun** [comment]
Closed as stale. The development of the C++ client has been permanently moved to http://github.com/apache/pulsar-client-cpp. Please open an issue there if it's still relevant.
