### ISSUE TITLE
garbage collection occured too often

### ISSUE THREAD

**Issue by w6m6** [apache/pulsar#8875]
**Describe the bug**
After we upgrade pulsar from 2.4.0 to 2.6.2, we found the frequency of garbage collection is much higher than v2.4.0 and the Journal Add latency of bookie is increased, which might related to the increase of gc frequency.

**Screenshots**
![WechatIMG90](https://user-images.githubusercontent.com/28854175/101601830-159b2200-3a38-11eb-8574-0345072f440b.jpeg)

**Comment by lhotari** [comment]
This is probably caused by https://github.com/apache/pulsar/commit/efa984bf5afd7af828622780e1522293fdaa19de . There's a fix in PR #8908 . /cc @sijie

**Comment by lhotari** [comment]
There's also a PR to enable Log4j2's Garbage Free logging mode, it's #8944 . Applying both #8908 and #8944 should reduce GC pressure. 

Since both PRs are simply changes to the bin/pulsar script, it would be easy to path the wrapper script to re-test with the changes. I have created a script to patch the apachepulsar/pulsar-all docker images for 2.6.2 and 2.7.0 here: https://github.com/lhotari/pulsar-docker-images-patch-log4j2-config

@w6m6 are you running Pulsar in k8s or do you run it without docker images? Would you be able to re-test with the patched bin/pulsar script? (see https://github.com/lhotari/pulsar-docker-images-patch-log4j2-config for patching the docker images)
