### ISSUE TITLE
k8s offload access denied

### ISSUE THREAD

**Issue by joncashe** [apache/pulsar#9044]
hello

I have a issue with the s3 tiered offload two exact configurations, using different buckets, one works and the other one doesn't i got this when i try to check the offload status after trying to trigger it manually with topics [offload](https://pulsar.apache.org/docs/en/pulsar-admin/#offload) (the one that doesnt work isnt a fresh start so it has some previous data) 

```
Error in offload

null

Reason: Error offloading: org.apache.bookkeeper.mledger.ManagedLedgerException: java.util.concurrent.CompletionException: org.jclouds.rest.AuthorizationException: Access Denied
```

I am using pulsar 2.6.1 i have set the following configuration in the brokers

    managedLedgerOffloadDriver: "aws-s3"
    s3ManagedLedgerOffloadRegion: "us-east-1"
    s3ManagedLedgerOffloadBucket: bucketname
    s3ManagedLedgerOffloadRole: rolename
    s3ManagedLedgerOffloadRoleSessionName: sessioname

the role name has the following perms both have the same the only difference its the bucket name, i even tried with s3 full access and no luck

```
{
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname",
                "arn:aws:s3:::bucktname/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

is there something else i can check between the two? 

appreciate any feedback 

thanks

**Comment by sijie** [comment]
From @joncashe : 

so after testing a little bit more im not sure why its happening but it seems i was using in my first config a s3 bucket and then i changed to a new one replacing the value in the s3ManagedLedgerOffloadBucket, but it seems the ledger its still trying to offload to the previous bucket the way i found this was when i give it full access to the s3 so this time i didnt get the access denied error and the offload was done to the first bucket i set

im trying to look which places are still pointing to the old s3 bucket because the broker.conf its using the new one i set in the s3ManagedLedgerOffloadBucket

any ideas?

thanks

**Comment by sijie** [comment]
@joncashe - Did you set the offload policies in the namespace policy? One of the possibilities is that you set the namespace policy. Otherwise, I don't expect the bucket is persisted somewhere else.

**Comment by joncashe** [comment]
@sijie thanks you were right although i replace the parameter it was still using the old bucket in the offload namespace policy

i was able to replace it through the pulsar-admin cli tool

do you know exactly in which file this change its applied?

i guess we can say its solved

thanks

**Comment by sijie** [comment]
The namespace policy is stored in zookeeper.

**Comment by sijie** [comment]
@joncashe I am closing this issue for now. If you have any other questions, feel free to reopen it or create a new one.
