### ISSUE TITLE
Can not use Avro 1.10 together with pulsar-client-admin

### ISSUE THREAD

**Issue by geomagilles** [apache/pulsar#9045]
**Describe the bug**
When I have gradle dependencies defined as  
```
api("org.apache.pulsar:pulsar-client-admin:2.7.0")
api("org.apache.pulsar:pulsar-client:2.7.0")
implementation("org.apache.avro:acro:1.10.0")
```
then `AvroSchema.of(...)` triggers 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/avro/data/JodaTimeConversions$TimestampConversion
```

**To Reproduce**

Adding `pulsar-client-admin` api dependency seems to have the curious side-effect to "unshade" avro in pulsar-client. 

(when having `implementation("org.apache.pulsar:pulsar-client-admin:2.7.0")` instead of `api("org.apache.pulsar:pulsar-client-admin:2.7.0")` the same bug occurs but only at runtime)

The exception is thrown from `AvroSchema.addLogicalTypeConversions` because `JodaTimeConversions` does not exist anymore for avro >= 1.10

**Expected behavior**
I should be able to use Avro >=1.10

**Comment by aahmed-se** [comment]
https://issues.apache.org/jira/browse/AVRO-2335

jodatime support has been removed in avro 1.10 we will have to default to jsr310 dates

**Comment by congbobo184** [comment]
@geomagilles you can set jsr310ConversionEnabled = true in schemaDefinition, then can support the jodaTime

**Comment by geomagilles** [comment]
> @geomagilles you can set `jsr310ConversionEnabled = true` in `schemaDefinition`, then can support the jodaTime

You may think so according to the code - but actually it does not help. I'm not sure why

**Comment by congbobo184** [comment]
@geomagilles Pulsar admin dependency avro-protobuf, it version is 1.9.1. AVRO 1.9.1 is conflict for 1.10.0, can you upgrade avro version from 1.10.0 to 1.9.1 :)

**Comment by geomagilles** [comment]
> @geomagilles Pulsar admin dependency avro, it version is 1.9.1. AVRO 1.9.1 is conflict for 1.10.0, can you upgrade avro version from 1.10.0 to 1.9.1 :)

I'm using Avro4k lib whose depends on Avro 1.10. Moreover, I'm writing a lib - currently this bug implied that lib users have to explicitly force AVRO 1.9.1. it's possible but really inconvenient.

**Comment by megfigura** [comment]
I hit a similar issue today where adding a dependency on pulsar-client-admin (2.6.0) caused compilation errors in other code in my project using protobuf. Checking the pulsar-client-admin jar, I see that its protobuf dependency (and others) are included inside and their packages are not [shaded / relocated.](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) This caused Eclipse to see the protobuf classes included in the pulsar-client-admin jar rather than the incompatible ones from the protobuf dependency I had defined in my pom.xml, hence the compilation error in my code.

Switching to the pulsar-client-admin-original / pulsar-client-original packages fixes my problem since this allows Maven to resolve dependencies as expected rather than running into "surprise dependencies" hidden away inside the pulsar jar.

Maybe pulsar should relocate the packages of its dependencies, or maybe the "original" version should be mentioned in the documentation. Like, "use _original_ if you have a complex application with many of its own dependencies."

**Comment by eolivelli** [comment]
This is my patch to fix the issue and upgrade Avro
#9898
Please take a look.

Eventually we could only pick the part about removing the JodaTimeConversion class usage and keep Avro 1.9.1 in Pulsar, but it is better to upgrade to the new version in order to keep up with the latest release.
