### ISSUE TITLE
Docs page for broker settings is misformatted; table is broken

### ISSUE THREAD

**Issue by zbentley** [apache/pulsar#9132]
**Describe the bug**

The configuration reference for broker settings at https://pulsar.apache.org/docs/ja/2.1.0-incubating/reference-configuration/ has a formatting issue which breaks the table for the broker settings.

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/ja/2.1.0-incubating/reference-configuration/
2. Scroll down to managedLedgerMaxEntriesPerLedger
3. Observe that table formatting breaks shortly after the bulleted list for managedLedgerMaxEntriesPerLedger conditions.

**Expected behavior**

The table should not be misformatted.

**Screenshots**

![image](https://user-images.githubusercontent.com/10999109/103674880-43975780-4f4d-11eb-9e6d-de1e8beeb1ab.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Additional context**
Issue is visible in Chrome and Safari.

**Comment by Jennifer88huang** [comment]
@zbentley Thanks for raising the issue. I've fixed in #9158, please check.

**Comment by h-j-13** [comment]
@Jennifer88huang here is another broken table in [pulsar/client-libraries-go](https://pulsar.apache.org/docs/zh-CN/client-libraries-go/)  Chinese version page

![image](https://user-images.githubusercontent.com/20575663/104163198-f590c100-5430-11eb-883a-d698cb90d3bc.png) 

Mac OSX / Chrome

**Comment by Jennifer88huang** [comment]
@h-j-13 Thank you for reporting the issue. I just checked the English website for [go client](https://pulsar.apache.org/docs/en/client-libraries-go/#consumers), it works well. So the issue lies in our [Crowdin project](), we'll check and fix it, and let you know the result.

**Comment by Jennifer88huang** [comment]
@h-j-13 I checked and found the reason now.
- The English version works well because the website renders markdown format well.
- The Chinese version does not work well because it judges the format based on periods, which is not quite right.
![image](https://user-images.githubusercontent.com/47805623/104178241-ef0c4480-5444-11eb-832b-fbfcb4e4eeee.png)

Solution options:
1. Refine the English version and add periods at the end of description, so a row works well in Crowdin.
2. When translating the Chinese version, fix it directly in Crowdin.

**Comment by Jennifer88huang** [comment]
@h-j-13 would you like to fix the issue?

**Comment by zbentley** [comment]
Thanks so much!

**Comment by h-j-13** [comment]
> @h-j-13 would you like to fix the issue?

i would like to do this, but don't kown how to use the `Crowdin`
