### ISSUE TITLE
Provide an DCOS Universe package for pulsar

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#917]
Similar as what Bookkeeper does at apache/bookkeeper#586, provide a pulsar package in DCOS universe.

**Comment by zhaijack** [comment]
@sijie , Sure, I would like to have a try on this.

**Comment by jiazhai** [comment]
Pulsar is composed of several apps (such as bookie, broker, monitor) together. But currently it only support to have one universe package for one app. Sadly, We may not able to do it currently.

Universe package could be treat as a wrap on Marathon. Marathon supports starting multiple apps from one json, which called a "[Marathon Application Groups](https://mesosphere.github.io/marathon/docs/application-groups.html)", this json is submitted to [/v2/groups endpoint](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-groups).

However, the [Cosmos (the DC/OS package manager)](https://github.com/dcos/cosmos/) doesn’t accept the same request, because it only accepts request for /v2/apps endpoint from [this code](https://github.com/dcos/cosmos/blob/master/cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala#L26), which is starting a single app.

There was already an [issue](https://github.com/mesosphere/universe/issues/569) opened to request a supporting for this group work in DCOS.

**Comment by zhaijack** [comment]
Pulsar is composed of several apps (such as bookie, broker, monitor) together. But currently it only support to have one universe package for one app. Sadly, We may not able to do it currently.

Universe package could be treat as a wrap on Marathon. Marathon supports starting multiple apps from one json, which called a "[Marathon Application Groups](https://mesosphere.github.io/marathon/docs/application-groups.html)", this json is submitted to [/v2/groups endpoint](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-groups).

However, the [Cosmos (the DC/OS package manager)](https://github.com/dcos/cosmos/) doesn’t accept the same request, because it only accepts request for /v2/apps endpoint from [this code](https://github.com/dcos/cosmos/blob/master/cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala#L26), which is starting a single app.

There was already an [issue](https://github.com/mesosphere/universe/issues/569) opened to request a supporting for this group work in DCOS.

**Comment by zhaijack** [comment]
would like to left this issue tracking the DCOS supporting work, and open another issue #924 for the marathon app groups work.

**Comment by sijie** [comment]
@zhaijack anything we need to do for this task? if not, can we close it?

**Comment by sijie** [comment]
close this since no one asks for it.

**Comment by jheinnic** [comment]
Aww...  I'm currently researching technologies for a new employer that has interest in Kafka and a significant existing data science investment in Python.  I'm strongly of an opinion that regulatory privacy compliance concerns will eventually require owning whatever streaming technology they deploy rather than delegating its operation to a 3rd party PaaS provider.

While exploring my options for resolving language impedance between an existing code and skills investment in Python and a JVM-first platform technology, I came across Apache Pulsar this afternoon.  Admittedly, I am just at the beginning of my investigation, but after recognizing that Pulsar is an actively maintained project that has decomposed the problem it addresses in a way that has enabled it to provide the language support not present in Kafka and noting that it has recently graduated from incubator status, the very next triage-style question I that led me to this very thread was, "What about DC/OS support?  Will installation/maintenance obscurities make diving deeper a non-starter?"

**Comment by jheinnic** [comment]
Ahh, but after posting my initial reaction to "no one asking for this", I examined the link to #950 and realized that the state of affairs is that DC/OS support may just be present in a different form than what I would have initially looked for.  I read further on...

**Comment by sijie** [comment]
@jheinnic the initial idea was to provide a full DC/OS support. @jiazhai developed #950. #950 was good enough for people who uses DC/OS. We didn't continue the effort due to there were no enough activities around DCOS support. so I closed the issues. 

If there are requirements for running Pulsar on DCOS, feel free to reopen this issue or create a new one with your requirements. We can look into it again.
