### ISSUE TITLE
CI is not running tests

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar#9526]
Today I have a PR that is not validated, this is the error on GitHub actions.

Basically GitHub is believing that this is a website only change and it is not performing tests

![Screenshot 2021-02-08 at 11 34 23](https://user-images.githubusercontent.com/9469110/107208301-b2127e00-6a01-11eb-8632-87655f2a24f1.png)

**Comment by eolivelli** [comment]
It happened at least in those two Pull requests:
https://github.com/apache/pulsar/pull/9448
https://github.com/apache/pulsar/pull/8590

**Comment by lhotari** [comment]
This issue has been reported as https://github.com/apache/pulsar-test-infra/issues/12 . It's a bug in https://github.com/apache/pulsar-test-infra/blob/master/diff-only/entrypoint.sh . 
The diff-only solution doesn't work well together with shallow clones. Because of performance and efficiency, the Pulsar workflows use a shallow clone of last 25 commits. That doesn't work together with diff-only solution when there are more than 25 commits in the PR. 
This must be fixed asap. However, the diff-only solution is not necessary at all. There's a "paths-ignore" feature in GitHub Actions that makes the diff-only solution obsolete. I'll create a PR to make that change.

**Comment by lhotari** [comment]
Changes to eliminate diff-only action completely in pulsar workflows: https://github.com/apache/pulsar/pull/9527

Fix to the bug in diff-only action: https://github.com/apache/pulsar-test-infra/pull/16

**Comment by eolivelli** [comment]
What's the status of this issue?
