### ISSUE TITLE
Pulsar Proxy HashedWheelTimer and Frame Exception

### ISSUE THREAD

**Issue by xuesongxs** [apache/pulsar#9783]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54351417/109797111-fa653a80-7c53-11eb-8cad-804755a63464.png)

![image](https://user-images.githubusercontent.com/54351417/109796913-b4a87200-7c53-11eb-9bba-66072cfbd6fa.png)

**Comment by codelipenghui** [comment]
Thanks @xuesongxs . Seems the problem is the proxy creates a Pulsar client for each connection since the proxy need to do the authentication by the client. Since each Pulsar client will create a HashedWheelTimer, so the error occurs and more HashedWheelTimer will waste a lot of cpu cycles(the tick time is 1ms in the Pulsar client).

I think we should make the HashedWheelTimer static in the Pulsar client.

**Comment by lhotari** [comment]
It turns out the PulsarClientImpl isn't needed at all in Pulsar Proxy. There's a PR #13836 to optimize the resource usage of Pulsar Proxy. This reduces 2 threads per proxied connection which will help improve Pulsar Proxy scalability. Please review #13836
